# Comandos PIP

In [1]:
%pip install --upgrade pip

Requirement already satisfied: pip in /home/matheus/anaconda3/lib/python3.12/site-packages (25.0.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install --upgrade Pillow

Requirement already satisfied: Pillow in /home/matheus/anaconda3/lib/python3.12/site-packages (11.1.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install pytesseract

Requirement already satisfied: pytesseract in /home/matheus/anaconda3/lib/python3.12/site-packages (0.3.13)
Requirement already satisfied: packaging>=21.3 in /home/matheus/anaconda3/lib/python3.12/site-packages (from pytesseract) (23.2)
Requirement already satisfied: Pillow>=8.0.0 in /home/matheus/anaconda3/lib/python3.12/site-packages (from pytesseract) (11.1.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
%pip install -qU langchain_community langchain_huggingface pymupdf

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-webui 0.5.12 requires langchain==0.3.7, but you have langchain 0.3.22 which is incompatible.
open-webui 0.5.12 requires langchain-community==0.3.7, but you have langchain-community 0.3.20 which is incompatible.
Note: you may need to restart the kernel to use updated packages.

# Imports

In [5]:
import os, shutil
os.environ["TESSDATA_PREFIX"] = r'/usr/share/tesseract-ocr/4.00/tessdata'

from tqdm.notebook import tqdm
import pandas as pd
from typing import Optional, List, Tuple
import matplotlib.pyplot as plt
from langchain_core.document_loaders import BaseLoader
from langchain_community.document_loaders.pdf import BasePDFLoader
from langchain_core.documents import Document as LCDocument
from pathlib import Path
import logging
from typing import Any, Dict, Iterator, Mapping, Optional, List, TYPE_CHECKING
from langchain_core.document_loaders import BaseBlobParser
from langchain_community.document_loaders.blob_loaders import Blob
import warnings
import fitz
from __future__ import annotations
import time
from datetime import timedelta
from pymupdf import FileDataError
from langchain.docstore.document import Document as LangChainDocument
from langchain.text_splitter import RecursiveCharacterTextSplitter
from transformers import AutoTokenizer
from langchain.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings, HuggingFacePipeline
from langchain_community.vectorstores.utils import DistanceStrategy
from transformers import pipeline
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from langchain_core.prompts import PromptTemplate, ChatMessagePromptTemplate, ChatPromptTemplate
import pytesseract
from PIL import Image

# LLM 🟥

## Document Loader (PyMuPDF)

In [6]:
if TYPE_CHECKING:
    import fitz.fitz

class PyMuPDFCustomParser(BaseBlobParser):
    """Parse `PDF` using `PyMuPDF`."""

    def __init__(
        self,
        text_kwargs: Optional[Mapping[str, Any]] = None,
    ) -> None:
        """Initialize the parser.

        Args:
            text_kwargs: Keyword arguments to pass to ``fitz.Page.get_text()``.
        """
        self.text_kwargs = text_kwargs or {}

    def lazy_parse(self, blob: Blob) -> Iterator[LCDocument]:  # type: ignore[valid-type]
        """Lazily parse the blob."""

        import fitz

        with blob.as_bytes_io() as file_path:  # type: ignore[attr-defined]
            
                if blob.data is None:  # type: ignore[attr-defined]
                    doc = fitz.open(file_path)
                else:
                    doc = fitz.open(stream=file_path, filetype="pdf")

                yield from [
                    LCDocument(
                        page_content=self._get_page_content(doc, page, blob),
                        metadata=self._extract_metadata(doc, page, blob),
                    )
                    for page in doc
                ]
    def _get_page_content(
        self, doc: fitz.fitz.Document, page: fitz.fitz.Page, blob: Blob
    ) -> str:
        """
        Get the text of the page using PyMuPDF and RapidOCR and issue a warning
        if it is empty.
        """
        content = page.get_text(**self.text_kwargs)
        images = page.get_images(full=True) 
        
        # if images:
        #    #print("Realizando OCR na pag {pag}".format(pag = page))
        #    retorno = self._extract_images_from_page(doc, page, images) 
        #    if ( retorno is not None):
        #        content += retorno
        #    else:
        #        retorno = self.extract_txt_saved_img('/home/pedro-nca/images/pdf_images')
        #        content += retorno
                
            



            
        # if not content:
        #     warnings.warn(
        #         f"Warning: Empty content on page "
        #         f"{page.number} of document {blob.source}"
        #     )

        return content

    def _extract_metadata(
        self, doc: fitz.fitz.Document, page: fitz.fitz.Page, blob: Blob
    ) -> dict:
        """Extract metadata from the document and page."""
        return dict(
            {
                "source": blob.source,  # type: ignore[attr-defined]
                "file_path": blob.source,  # type: ignore[attr-defined]
                "page": page.number,
                "total_pages": len(doc),
            },
            **{
                k: doc.metadata[k]
                for k in doc.metadata
                if isinstance(doc.metadata[k], (str, int))
            },
        )

    # def _extract_images_from_page(
    #     self, doc: fitz.fitz.Document, page: fitz.fitz.Page, images
    # ) -> str:
    #     """Extract images from page and get the text with RapidOCR."""
    #     import fitz
    #     for item in images:
            
    #         xref = item[0]
    #         smask = item[1]
    #         if smask > 0:
    #             pix0 = fitz.Pixmap(doc.extract_image(xref)["image"])
    #             if pix0.alpha: 
    #                 pix0 = fitz.Pixmap(pix0, 0)

    #                 #print(str(page)[6])
    #                 #pix0.save(filename='/home/pedro-nca/images/pdf_images/image'+str(page)[6]+'.jpeg')
    #                 #pix._writeIMG(output, format_=1, jpg_quality=)
    #                 #print("=== Convertendo PDF para imagem: {img} ===".format(img=output))
    #                 #print("PYTE ==== {text}".format(text=text))
    #                 pdfdata = pix0.pdfocr_tobytes()  
    #                 ocrpdf = fitz.open("pdf", pdfdata)  
    #                 ocrtext = ocrpdf[0].get_text()  
                    
    #                 return ocrtext
    #             mask = fitz.Pixmap(doc.extract_image(smask)["image"])
            
    #         if "/ColorSpace" in doc.xref_object(xref, compressed=True):
    #             pix0 = fitz.Pixmap(doc, xref)
    #             pix0 = fitz.Pixmap(fitz.csRGB, pix0)
    #             save_path = '/home/pedro-nca/images/pdf_images/image'+str(page)[6]+'.png'
    #             pix0.save(filename=save_path)
                
                


            # if pix.colorspace is None:
            #     print("ENTRO PARA CONVERSÃO ")
            #     pix = fitz.Pixmap(fitz.csRGB, pix) 
            #print(pix.colorspace)
            # if pix.colorspace.name not in (fitz.csGRAY.name, fitz.csRGB.name, fitz.csCMYK.name):
            #     #print("Essa imagem pode ser uma máscara.")
            #     #pix = fitz.Pixmap(fitz.csRGB, pix)
            #     return ''
            # else:
    
    def extract_txt_saved_img(self, img_folder_path):
        for arq in os.listdir(img_folder_path):
            if arq.endswith('.png'):
                img_file_path = os.path.join(img_folder_path, arq)                    
                text_each_img =  str(((pytesseract.image_to_string(Image.open(img_file_path), lang="por"))))
                return text_each_img

In [7]:
class PyMuPDFCustomLoader(BasePDFLoader):
    def __init__(self,
        file_path: str,
        *,
        headers: Optional[Dict] = None,
        **kwargs: Any,):
        
        try:
            import fitz  # noqa:F401
        except ImportError:
            raise ImportError(
                "`PyMuPDF` package not found, please install it with "
                "`pip install pymupdf`"
            )
        super().__init__(file_path, headers=headers)
        self.text_kwargs = kwargs
    
    def _lazy_load(self, **kwargs: Any) -> Iterator[LCDocument]:
        # if kwargs:
        #     logger.warning(
        #         f"Received runtime arguments {kwargs}. Passing runtime args to `load`"
        #         f" is deprecated. Please pass arguments during initialization instead."
        #     )

        text_kwargs = {**self.text_kwargs, **kwargs}
        parser = PyMuPDFCustomParser(
            text_kwargs=text_kwargs
        )
        if self.web_path:
            blob = Blob.from_data(open(self.file_path, "rb").read(), path=self.web_path)  # type: ignore[attr-defined]
        else:
            blob = Blob.from_path(self.file_path)  # type: ignore[attr-defined]
        yield from parser.lazy_parse(blob)

    def load(self, **kwargs: Any) -> List[LCDocument]:
        return list(self._lazy_load(**kwargs))

    def lazy_load(self) -> Iterator[LCDocument]:
        yield from self._lazy_load()

## Funções de Utilidades

In [8]:
# TXT = []
# for arq in os.listdir('/home/pedro-nca/images/pdf_images'):
#     if arq.endswith('.png'):
#         img_file_path = os.path.join('/home/pedro-nca/images/pdf_images', arq)                    
#         text_each_img =  str(((pytesseract.image_to_string(Image.open(img_file_path), lang="por"))))
#         TXT.append(text_each_img)

In [9]:
def delete_files_in_folder(folder_path):
    for filename in os.listdir(folder_path):
        file_path = os.path.join(folder_path, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print('Failed to delete %s. Reason: %s' % (file_path, e))

## 1 - Carregamento dos PDF's

In [10]:
#path_folder = "/home/pedro-nca/pdf_mock/"
path_folder = '/home/matheus/Benchmark/'

from langchain_community.document_loaders import PyMuPDFLoader, PyPDFLoader
DOC_DATABASE = []

for folder_name in os.listdir(path_folder):
    pdf_folder_path= path_folder+folder_name
    for arq in os.listdir(pdf_folder_path):
        if arq.endswith('.pdf'):
               try:
                    pdf_file_path = os.path.join(pdf_folder_path, arq)                    
                    loader = PyMuPDFCustomLoader(file_path=pdf_file_path)
                    #loader = PyMuPDFLoader(pdf_file_path, extract_images=True)
                    #loader = PyPDFLoader(file_path=pdf_file_path, extract_images=True)
                    #getTables(pdf_file_path)
                    DOC_DATABASE.extend(loader.load())                
                    #delete_files_in_folder('/home/pedro-nca/images/pdf_images')
               except FileDataError:
                     pass
           

            

#DOC_DATABASE

In [11]:
DOC_DATABASE

[Document(metadata={'source': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'file_path': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'page': 0, 'total_pages': 20, 'format': 'PDF 1.5', 'title': 'Of', 'author': 'Cristina Girardi', 'subject': '', 'keywords': '', 'creator': 'Microsoft® Word 2013', 'producer': 'Microsoft® Word 2013', 'creationDate': "D:20230915130750-03'00'", 'modDate': "D:20230918085208-03'00'", 'trapped': ''}, page_content=' \n \n \nEXAME NACIONAL PARA INGRESSO NA  \nPÓS-GRADUAÇÃO EM COMPUTAÇÃO/2023 \n \nEXAME POSCOMP 2023 \nLeia atentamente e cumpra rigorosamente as instruções que seguem, pois elas são parte integrante \ndas provas e das normas que regem esse certame. \n1. Certifique-se de que o ambiente de prova: \n- contém 70 (setenta) questões; \n2. Cada questão oferece 5 (cinco) alternativas de respostas, representadas pelas letras A, B, C, D e \nE, sendo apenas 1 (uma) a resposta correta. \n3. Será respeitado o tempo para realização da prova conforme previsto em edital. \n4. A responsabilidade referente à interpretação dos conteúdos das questões é exclusiva do candidato. \n5. Os gabaritos preliminares da prova objetiva serão divulgados na data descrita no Cronograma de \nExecução desse certame. \n \nV1_23/08/2023 11:31:44 \nQR \ncode \n'),
 Document(metadata={'source': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'file_path': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'page': 1, 'total_pages': 20, 'format': 'PDF 1.5', 'title': 'Of', 'author': 'Cristina Girardi', 'subject': '', 'keywords': '', 'creator': 'Microsoft® Word 2013', 'producer': 'Microsoft® Word 2013', 'creationDate': "D:20230915130750-03'00'", 'modDate': "D:20230918085208-03'00'", 'trapped': ''}, page_content='761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nMATEMÁTICA \n \nQUESTÃO 01 – Utilize o método de Eliminação de Gauss para resolver o sistema a seguir: \n \n-3x + y + z = 1 \nx – 2y + z = 4 \n-x + y − 3z = -7 \n \nA) (0, -1, 2) \nB) (0, 1, 0) \nC) (2, 0, 2) \nD) (2, 1, 2)  \nE) (-1, -1, -1) \n \n \nQUESTÃO 02 – Determine o valor de x para que o vetor (1, x, 5) ∈ R3 pertença ao subespaço          \n<(1, 2, 3), (1, 1, 1)> \n \nA) x = 0 \nB) x = -1 \nC) x = 1 \nD) x = 3 \nE) x = 7 \n \n \nQUESTÃO 03 – Determine o polinômio característico de J: \n  \nJ = (\n2\n−2\n1\n1\n−1\n1\n1\n−2\n2\n) \n \nA) 0 \nB) x \nC) (1 − x) \nD) (1 − x)² \nE) (1 − x)³ \n \n \nQUESTÃO 04 – Nos jogos da Mega-Sena, são sorteados a cada concurso 6 números no intervalo de \n1 a 60. Leva o prêmio quem acertar os 6 números sorteados. O apostador, ao fazer um jogo, pode \noptar por preencher um bilhete com 6, 7, 8 ou 9 números escolhidos. Se o apostador registra um \nbilhete com 8 números escolhidos, quantos bilhetes de 6 números ele faria com os mesmos             \n8 números escolhidos? \n \nA) 56 \nB) 8! \nC) 6! \nD) 28 \nE) 72 \n \n \nQUESTÃO 05 – Recentemente, com a pandemia de Covid-19, houve grande interesse em \ndeterminar conjuntos de regiões (de países, estados, municípios, etc.) com alta incidência da doença, \ncom o objetivo de determinar políticas de mitigação da doença nesses locais. Nesse sentido, dado \num mapa subdividido em regiões, um cluster é definido como sendo um subconjunto de regiões \ndesse mapa (nesse caso, pode ser formado por regiões que não fazem fronteira entre si). Qual o \nnúmero de possíveis clusters para um mapa com 10 regiões? \n \nA) 1024 \nB) 10 \nC) 100 \nD) 512 \nE) 20 \n'),
 Document(metadata={'source': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'file_path': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'page': 2, 'total_pages': 20, 'format': 'PDF 1.5', 'title': 'Of', 'author': 'Cristina Girardi', 'subject': '', 'keywords': '', 'creator': 'Microsoft® Word 2013', 'producer': 'Microsoft® Word 2013', 'creationDate': "D:20230915130750-03'00'", 'modDate': "D:20230918085208-03'00'", 'trapped': ''}, page_content='761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 06 – Um anagrama é uma nova palavra formada pela permutação de letras de uma \npalavra. Essa nova palavra não precisa fazer sentido. Um anagrama de POSCOMP, por exemplo, seria \nMOCPSOP. Quantos são os anagramas da palavra POSCOMP? \n \nA) 126 \nB) 252 \nC) 1260 \nD) 2520 \nE) 5040 \n \n \nQUESTÃO 07 – Calcule o lim\n𝑥→10−3 𝑙𝑜𝑔(10 ∙𝑥). \n \nA) 0 \nB) -3 \nC) -2 \nD) 1 \nE) 100 \n \n \nQUESTÃO 08 – Determine os intervalos da função 𝑓(𝑥) = 5𝑥²√𝑥+ 1. \n \nA) 𝐼1 = (−1, −\n4\n5) ; 𝐼2 = (−\n4\n5 , 0); 𝐼3 = (0, ∞) \nB) 𝐼1 = (−∞, −\n4\n5) ; 𝐼2 = (−\n4\n5 , 0) ; 𝐼3 = (0, ∞) \nC) 𝐼1 = (−1, 0); 𝐼2 = (0, 1); 𝐼3 = (1, ∞) \nD) 𝐼1 = (−1, 1); 𝐼2 = (1,\n5\n4) ; 𝐼3 = (\n5\n4 , ∞) \nE) 𝐼1 = (−∞, −1); 𝐼2 = (−1, 1); 𝐼3 = (1, ∞) \n \n \nQUESTÃO 09 – Calcule o vetor gradiente da função 𝑓(𝑥, 𝑦) = 𝑒−𝑥𝑠𝑒𝑛(𝑥+ 𝑦) no ponto 𝑃 (0, 𝜋). \n \nA) ∇𝑓(0, 𝜋) = (0\n1) \nB) ∇𝑓(0, 𝜋) = (1\n1) \nC) ∇𝑓(0, 𝜋) = (−1\n1 ) \nD) ∇𝑓(0, 𝜋) = (−1\n−1) \nE) ∇𝑓(0, 𝜋) = (0\n0) \n \n \nQUESTÃO 10 – Dados os vetores u(3, 3, 2), v(5, -2, 1) e w(1, -1, 0), calcule a e b tal que             \nu = av + bw. \n \nA) a = 2 e b = -7 \nB) a = -1 e b = 5 \nC) a = 5 e b = -3 \nD) a = 3 e b = -9 \nE) a = -6 e b = 1 \n \n \n \n'),
 Document(metadata={'source': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'file_path': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'page': 3, 'total_pages': 20, 'format': 'PDF 1.5', 'title': 'Of', 'author': 'Cristina Girardi', 'subject': '', 'keywords': '', 'creator': 'Microsoft® Word 2013', 'producer': 'Microsoft® Word 2013', 'creationDate': "D:20230915130750-03'00'", 'modDate': "D:20230918085208-03'00'", 'trapped': ''}, page_content='761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 11 – Calcule o vetor diretor da interseção dos seguintes planos: \n \nx + 2y + z = 3 \n2x – y +3z = 4 \n \nA) (1, 5, 7) \nB) (1, 1, 0) \nC) (1, 1, 1) \nD) (7, -1, -5) \nE) (5, 1, 5) \n \n \nQUESTÃO 12 – Determine a distância aproximada entre o ponto J(3, 1) e a reta  \ns : 6x – 2y + 11 = 0. \n \nA) 1,3 \nB) 2,6 \nC) 4,3 \nD) 12,1 \nE) 18,5 \n \n \nQUESTÃO 13 – Analise a seguinte proposição: "Existe pelo menos uma universidade em que todos \nos cursos têm, pelo menos, 100 alunos". A negação dessa proposição é logicamente equivalente à \nproposição: \n \nA) Em todas as universidades existe pelo menos um curso que possui, no máximo, 99 alunos. \nB) Em no máximo uma universidade existe um curso que possui, no máximo, 101 alunos. \nC) Há uma universidade em que existe pelo menos um curso com, no máximo, 99 alunos. \nD) Em cada universidade existe pelo menos um curso que possui, pelo menos, 100 alunos. \nE) Existe nenhuma universidade em que os cursos possuam, no máximo, 100 alunos. \n \n \nQUESTÃO 14 – Sendo p e q proposições simples, considere a proposição composta E(p,q), cujos \nvalores lógicos estão na tabela verdade a seguir: \n \np \nq \nE(p,q) \nF \nF \nV \nF \nV \nV \nV \nF \nF \nV \nV \nV \n \nQual é o valor da expressão E? \n \nA) P–>q \nB) p ou q \nC) q–>p \nD) p ou ~q \nE) (~p)→(p ou q) \n \n \nQUESTÃO 15 – A expressão lógica p→q é equivalente a: \n \nA) ~p∧~q \nB) ~p→q \nC) p→~q \nD) ~q->~p \nE) q→p \n \n \n'),
 Document(metadata={'source': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'file_path': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'page': 4, 'total_pages': 20, 'format': 'PDF 1.5', 'title': 'Of', 'author': 'Cristina Girardi', 'subject': '', 'keywords': '', 'creator': 'Microsoft® Word 2013', 'producer': 'Microsoft® Word 2013', 'creationDate': "D:20230915130750-03'00'", 'modDate': "D:20230918085208-03'00'", 'trapped': ''}, page_content='761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 16 – Utilizando as leis de Morgan, obtenha uma expressão em forma de somas de \nprodutos para a seguinte função: \n \n𝐹= (𝑥+ 𝑦)(𝑥𝑦̅ + 𝑧)\n̅̅̅̅̅̅̅̅̅̅̅\n̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅ \n \nA) 𝑥̅ + 𝑥̅𝑧+ 𝑦 \nB)  𝑥𝑦\n̅̅̅ + 𝑥̅𝑦+ 𝑦 \nC) 𝑥̅𝑦+ 𝑥̅𝑦+ 𝑧 \nD) 𝑦̅ + 𝑧 \nE) 𝑥𝑦\n̅̅̅ + 𝑥̅𝑦 \n \n \nQUESTÃO 17 – A partir do seguinte circuito, apresentado na Figura 1, obtenha a equação de saída \nem soma de produtos (simplifique por álgebra de Boole). \n \n \nFigura 1 \n \nA) 𝑍= 𝐴𝐵̅ + 𝐴𝐵\n̅̅̅̅ + 𝐵𝐶 \nB) 𝑍=  𝐴𝐵̅ + 𝐵𝐶 \nC) 𝑍=  𝐴𝐵+ 𝐵𝐶\n̅̅̅̅ \nD) 𝑍=  𝐴𝐵̅ + 𝐴𝐵  \nE) 𝑍= 𝐴𝐵\n̅̅̅̅ + 𝐵 \n \n \nQUESTÃO 18 – Usando os conjuntos de dados A = {1, 4, 2, 6, 8, 10}, B = {1, 4, 6, 10},  \nC = {6, 4, 1, 10}, D = {6, 4, 1}, qual das seguintes alternativas é INCORRETA? \n \nA) A ⊆ B \nB) D ⊆ A \nC) B = C \nD) B ⊆ A \nE) A ≠ B \n \n \nQUESTÃO 19 – Com base na Tabela 1, calcule a média da seguinte amostra de número de filhos \nque têm as famílias que participaram da enquete: \n \nNº filho (Xi) \n0 1 2 3 4 \nNº famílias (ni) \n5 6 8 4 2 \nTabela 1 \n \nA) 1,12 \nB) 1,68 \nC) 2,11 \nD) 2,87 \nE) 3,21 \n \n \n \n \n \n'),
 Document(metadata={'source': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'file_path': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'page': 5, 'total_pages': 20, 'format': 'PDF 1.5', 'title': 'Of', 'author': 'Cristina Girardi', 'subject': '', 'keywords': '', 'creator': 'Microsoft® Word 2013', 'producer': 'Microsoft® Word 2013', 'creationDate': "D:20230915130750-03'00'", 'modDate': "D:20230918085208-03'00'", 'trapped': ''}, page_content='761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 20 – Em uma linha de produção, sabe-se que a probabilidade de ter uma peça com \ndefeito é de 0,05. Se o conjunto de unidades determinadas constitui um conjunto de ensaios \nindependentes, qual é a probabilidade de que pelo menos uma peça se encontre com defeito em um \ntotal de 10 unidades? \n \nA) 10,0% \nB) 40,0% \nC) 50,0% \nD) 80,0% \nE) 100,0% \n \nFUNDAMENTOS DA COMPUTAÇÃO \n \nQUESTÃO 21 – Sobre os conceitos de complexidade de algoritmos, é correto afirmar que: \n \nA) O espaço requerido por um algoritmo sobre uma dada entrada pode ser medido pelo número de \nexecuções de algumas operações.  \nB) A complexidade de tempo usa como medida de desempenho a quantidade de memória necessária \npara a execução do algoritmo. \nC) A complexidade média é definida pelo crescimento da complexidade para entradas \nsuficientemente grandes.  \nD) A complexidade assintótica dá o valor esperado: a média dos esforços, levando em conta a \nprobabilidade de ocorrência de cada entrada. \nE) A complexidade pessimista de um algoritmo fornece seu desempenho no pior caso: o pior \ndesempenho que se pode esperar. Aqui, pode-se considerar os desempenhos sobre todas as \nentradas com tamanho n.  \n \n \nQUESTÃO 22 – Qual das seguintes afirmações é verdadeira sobre a análise de algoritmos \nrecursivos? \n \nA) A complexidade de tempo de um algoritmo recursivo é sempre mais rápida do que a de um \nalgoritmo iterativo equivalente. \nB) A complexidade de espaço de um algoritmo recursivo é sempre menor do que a de um algoritmo \niterativo equivalente. \nC) A análise de complexidade de um algoritmo recursivo é sempre mais fácil do que a de um \nalgoritmo iterativo equivalente. \nD) Algoritmos recursivos nunca podem sofrer de problemas de estouro de pilha (stack overflow). \nE) A escolha adequada da estrutura de dados pode reduzir o tempo e o espaço necessários para a \nexecução de algoritmos recursivos. \n \n \nQUESTÃO 23 – Considere o seguinte trecho de código: \n \nfor (i = 1; i <= n; i++) { \n    for (j = 1; j <= m; j++) { \n        // instruções O(1) \n    } \n} \n \nQual das seguintes afirmações é verdadeira sobre a complexidade assintótica desse trecho de \ncódigo? \n \nA) A complexidade é O(n) se m for uma constante, e O(m) se n for uma constante. \nB) A complexidade é O(n log m) se m for uma constante, e O(m log n) se n for uma constante. \nC) A complexidade é O(n + m) se n e m forem do mesmo tamanho. \nD) A complexidade é O(1) em todos os casos. \nE) A complexidade é O(nm) em todos os casos. \n \n \n \n \n'),
 Document(metadata={'source': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'file_path': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'page': 6, 'total_pages': 20, 'format': 'PDF 1.5', 'title': 'Of', 'author': 'Cristina Girardi', 'subject': '', 'keywords': '', 'creator': 'Microsoft® Word 2013', 'producer': 'Microsoft® Word 2013', 'creationDate': "D:20230915130750-03'00'", 'modDate': "D:20230918085208-03'00'", 'trapped': ''}, page_content='761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 24 – Sobre funções Hash, é correto afirmar que: \n \nA) O método de divisão funciona em duas etapas. Na primeira etapa, multiplica-se a chave k por \numa constante A na faixa 0<A<1 e extrai-se a parte fracionária de kA. Na segunda etapa, \nmultiplica-se esse valor por m e toma-se o piso do resultado.  \nB) Em endereçamento aberto, todos os elementos ficam na própria tabela de espelhamento. Isto é, \ncada entrada da tabela contém um elemento do conjunto dinâmico ou NIL. Ao procurar um \nelemento, examina-se sistematicamente as posições da tabela até encontrar o elemento desejado \nou até confirmar que o elemento não está na tabela.  \nC) No método de encadeamento não existe nenhuma lista e nenhum elemento fora da tabela.  \nD) O hashing pode proporcionar excelente desempenho no pior caso, quando o conjunto de chaves \né dinâmico, isto é, assim que as chaves são armazenadas na tabela, o conjunto de chaves muda \nautomaticamente de tempos em tempos.  \nE) No método de multiplicação, mapeia-se uma chave k para uma de m posições, tomando o resto \nda divisão de k por m.  \n \n \nQUESTÃO 25 – Sobre as árvores binárias de busca, é correto afirmar que: \n \nA) Seja x um nó em uma árvore de busca binária. Se y é um nó na subárvore esquerda de x, então \ny.chave \uf0b3 x.chave. Se y é um nó na subárvore direita de x, então x.chave \uf0a3  y.chave. \nB) A propriedade de árvore de busca que permite imprimir todas as chaves em sequência ordenada \npor meio de um simples algoritmo recursivo é denominada percurso de árvore em pré-ordem.  \nC) Para excluir um nó z de uma árvore de busca binária T, se z tem apenas um filho, então \nsimplesmente o removemos modificando seu pai de modo a substituir z por NIL como seu filho.   \nD) Para excluir um nó z de uma árvore de busca binária T, se z tem dois filhos, então elevamos o \nprimeiro filho para que ocupe a posição de z na árvore modificando o pai de z de modo a substituir \nz pelo filho de z.  \nE) Para encontrar um nó em uma árvore de busca binária cuja chave é um mínimo, deve-se seguir \nos ponteiros de filhos da esquerda desde a raiz até encontrar um valor NIL.  \n \n \nQUESTÃO 26 – A ordenação ________________ determina, para cada elemento de entrada x, o \nnúmero de elementos menores que x e usa essa informação para inserir o elemento x diretamente \nem sua posição no arranjo de saída. Por exemplo, se 17 elementos forem menores que x, então x \npertence à posição de saída 18.  \n \nAssinale a alternativa que preenche corretamente a lacuna do trecho acima.  \n \nA) mergesort \nB) quicksort \nC) por contagem \nD) por fila de prioridade \nE) por intercalação com sentinela \n \n \nQUESTÃO 27 – Quais são os valores em decimal do binário (8 bits) 10011001, considerando a \nrepresentação sem sinal e em complemento de 2, respectivamente? \n \nA) 153, -102 \nB) 100, -101 \nC) 153, -103 \nD) 129, 103 \nE) 1, -1 \n \n \n \n \n \n \n \n'),
 Document(metadata={'source': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'file_path': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'page': 7, 'total_pages': 20, 'format': 'PDF 1.5', 'title': 'Of', 'author': 'Cristina Girardi', 'subject': '', 'keywords': '', 'creator': 'Microsoft® Word 2013', 'producer': 'Microsoft® Word 2013', 'creationDate': "D:20230915130750-03'00'", 'modDate': "D:20230918085208-03'00'", 'trapped': ''}, page_content='761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 28 – Qual é o resultado da seguinte fórmula Infixo A+B*(C-D*(E-F)-G*H)-I*3 convertida \npara a notação polonesa? \n \nA) A+*(B*(C-(D*(E-(F-G*H-I*3))))) \nB) A+B*C-D*E-F-G*H-I*3+*-*-*-*+ \nC) +*-*--*A -*ABCDEFGHI3 \nD) ABCDEF-*-GH*-*+I3*- \nE) ABCDEFGHI3+*-*-*-*- \n \n \nQUESTÃO 29 – O computador tem um tempo de acesso à memória principal de 60 ns. Queremos \nreduzir esse tempo para 20 ns adicionando no cache. Qual a velocidade do cache (tempo de acesso) \nse pudermos esperar uma probabilidade de 90% de acerto? \n \nA) 04 ns. \nB) 14 ns. \nC) 24 ns. \nD) 54 ns. \nE) 84 ns. \n \n \nQUESTÃO 30 – Considere um sistema numérico binário com 8 bits e o uso do complemento de 2 \npara representação de números inteiros para a realização da operação 4910 −12010. Com base nisso, \nanalise as assertivas abaixo, assinalando V, se verdadeiras, ou F, se falsas. \n \n(  ) O sistema numérico com essas características pode representar valores entre +255 e -256. \n(  ) O resultado da operação será representado pelo valor 101110012. \n(  ) Há um estouro de registro nessa operação quando feita nesse sistema. \n(  ) A operação de subtração é realizada ao somar a representação de complemento de 2 de 12010 \ncom a representação binária de 4910. \n \nA ordem correta de preenchimento dos parênteses, de cima para baixo, é: \n \nA) V – F – F – V. \nB) V – V – F – F. \nC) V – F – V – F. \nD) F – F – V – V. \nE) F – V – F – V. \n \n \nQUESTÃO 31 – Considere um circuito sequencial composto por um flip-flop JK e dois flip-flops. Para \nfins de simplicidade, o sinal de clock (CLK) está omitido, porém assuma que todos os componentes \nestão sincronizados nele. O diagrama do circuito é apresentado na Figura 2 abaixo: \n \nFigura 2 \n \nDado o estado inicial 𝑄0 = 𝑄1 = 𝑄2 = 1, informe quantas vezes o sinal será resetado (ou seja, será \nmudado para zero) depois de 6 ciclos de clock, sendo 𝐴= 𝐵= 1: \n \nA) 0 \nB) 1 \nC) 2 \nD) 3 \nE) 4 \n \n \n \n'),
 Document(metadata={'source': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'file_path': '/home/matheus/Benchmark/eh/0761.001_Exame_POSCOMP_2023.pdf', 'page': 8, 'total_pages': 20, 'format': 'PDF 1.5', 'title': 'Of', 'author': 'Cristina Girardi', 'subject': '', 'keywords': '', 'creator': 'Microsoft® Word 2013', 'producer': 'Microsoft® Word 2013', 'creationDate': "D:20230915130750-03'00'", 'modDate': "D:20230918085208-03'00'", 'trapped': ''}, page_content='761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 32 – Considere o circuito combinacional composto por portas lógicas NOT, AND e XOR, \nalém de um multiplexador, conforme a Figura 3, e analise as assertivas abaixo: \n \n \nFigura 3 \n \nI. A expressão (𝐴𝐵+ 𝐴𝐵) ∙𝐶 representa a função booleana que define o valor de S. \nII. A expressão 𝐵⊗𝐴⊕𝐶 representa a função booleana que define o valor de T. \nIII. O circuito contém a função de um somador binário completo, com entrada de sinais de dois \noperandos e do transporte, e saída do sinal de soma e do transporte. \n \nQuais estão corretas? \n \nA) Apenas I. \nB) Apenas II. \nC) Apenas III. \nD) Apenas I e III. \nE) I, II e III. \n \n \nQUESTÃO 33 – Considere o seguinte código em Linguagem C (Compilador Ansi C):  \n \n  int a = 2, b = 4, c = -1; \n  int *ptx, *pty, *ptz; \n  ptx = &a; \n  pty = &b; \n  ptz = &c; \n   \n  printf ("%d %d %d %d %d %d \\n", a, b, c, *ptx, *pty, *ptz); \n  a = (*ptx) * (*pty); \n  b = *ptz + 1; \n  ++c; \n  printf ("%d %d %d %d %d %d \\n", a, b, c, *ptx, *pty, *ptz); \n \nAssinale a alternativa que corresponde à saída na tela. \n \nA) 2  2 -1 2 4 -1 \n8 -1  0 8 0  0 \n \nB) 2 4 -1 2 2 -1 \n2 0 -1 2 0 -1 \n \nC) 2 2 -1 2 4  0 \n8 0 -1 8 0 -1 \n \nD) 2 4 -1 2 4 -1 \n8 0 -1 8 0 -1 \n \nE) 2 4 -1 2 4 -1 \n8 0  0 8 0  0 \n'),

In [12]:
texto_questoes = []
for doc in DOC_DATABASE:
    texto_questoes.append(doc.page_content)

In [13]:
texto_questoes = texto_questoes[1:]
texto_questoes

['761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nMATEMÁTICA \n \nQUESTÃO 01 – Utilize o método de Eliminação de Gauss para resolver o sistema a seguir: \n \n-3x + y + z = 1 \nx – 2y + z = 4 \n-x + y − 3z = -7 \n \nA) (0, -1, 2) \nB) (0, 1, 0) \nC) (2, 0, 2) \nD) (2, 1, 2)  \nE) (-1, -1, -1) \n \n \nQUESTÃO 02 – Determine o valor de x para que o vetor (1, x, 5) ∈ R3 pertença ao subespaço          \n<(1, 2, 3), (1, 1, 1)> \n \nA) x = 0 \nB) x = -1 \nC) x = 1 \nD) x = 3 \nE) x = 7 \n \n \nQUESTÃO 03 – Determine o polinômio característico de J: \n  \nJ = (\n2\n−2\n1\n1\n−1\n1\n1\n−2\n2\n) \n \nA) 0 \nB) x \nC) (1 − x) \nD) (1 − x)² \nE) (1 − x)³ \n \n \nQUESTÃO 04 – Nos jogos da Mega-Sena, são sorteados a cada concurso 6 números no intervalo de \n1 a 60. Leva o prêmio quem acertar os 6 números sorteados. O apostador, ao fazer um jogo, pode \noptar por preencher um bilhete com 6, 7, 8 ou 9 números escolhidos. Se o apostador registra um \nbilhete com 8 números escolhidos, quantos bilhetes de 6 números ele faria com os mesmos             \n8 números escolhidos? \n \nA) 56 \nB) 8! \nC) 6! \nD) 28 \nE) 72 \n \n \nQUESTÃO 05 – Recentemente, com a pandemia de Covid-19, houve grande interesse em \ndeterminar conjuntos de regiões (de países, estados, municípios, etc.) com alta incidência da doença, \ncom o objetivo de determinar políticas de mitigação da doença nesses locais. Nesse sentido, dado \num mapa subdividido em regiões, um cluster é definido como sendo um subconjunto de regiões \ndesse mapa (nesse caso, pode ser formado por regiões que não fazem fronteira entre si). Qual o \nnúmero de possíveis clusters para um mapa com 10 regiões? \n \nA) 1024 \nB) 10 \nC) 100 \nD) 512 \nE) 20 \n',
 '761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 06 – Um anagrama é uma nova palavra formada pela permutação de letras de uma \npalavra. Essa nova palavra não precisa fazer sentido. Um anagrama de POSCOMP, por exemplo, seria \nMOCPSOP. Quantos são os anagramas da palavra POSCOMP? \n \nA) 126 \nB) 252 \nC) 1260 \nD) 2520 \nE) 5040 \n \n \nQUESTÃO 07 – Calcule o lim\n𝑥→10−3 𝑙𝑜𝑔(10 ∙𝑥). \n \nA) 0 \nB) -3 \nC) -2 \nD) 1 \nE) 100 \n \n \nQUESTÃO 08 – Determine os intervalos da função 𝑓(𝑥) = 5𝑥²√𝑥+ 1. \n \nA) 𝐼1 = (−1, −\n4\n5) ; 𝐼2 = (−\n4\n5 , 0); 𝐼3 = (0, ∞) \nB) 𝐼1 = (−∞, −\n4\n5) ; 𝐼2 = (−\n4\n5 , 0) ; 𝐼3 = (0, ∞) \nC) 𝐼1 = (−1, 0); 𝐼2 = (0, 1); 𝐼3 = (1, ∞) \nD) 𝐼1 = (−1, 1); 𝐼2 = (1,\n5\n4) ; 𝐼3 = (\n5\n4 , ∞) \nE) 𝐼1 = (−∞, −1); 𝐼2 = (−1, 1); 𝐼3 = (1, ∞) \n \n \nQUESTÃO 09 – Calcule o vetor gradiente da função 𝑓(𝑥, 𝑦) = 𝑒−𝑥𝑠𝑒𝑛(𝑥+ 𝑦) no ponto 𝑃 (0, 𝜋). \n \nA) ∇𝑓(0, 𝜋) = (0\n1) \nB) ∇𝑓(0, 𝜋) = (1\n1) \nC) ∇𝑓(0, 𝜋) = (−1\n1 ) \nD) ∇𝑓(0, 𝜋) = (−1\n−1) \nE) ∇𝑓(0, 𝜋) = (0\n0) \n \n \nQUESTÃO 10 – Dados os vetores u(3, 3, 2), v(5, -2, 1) e w(1, -1, 0), calcule a e b tal que             \nu = av + bw. \n \nA) a = 2 e b = -7 \nB) a = -1 e b = 5 \nC) a = 5 e b = -3 \nD) a = 3 e b = -9 \nE) a = -6 e b = 1 \n \n \n \n',
 '761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 11 – Calcule o vetor diretor da interseção dos seguintes planos: \n \nx + 2y + z = 3 \n2x – y +3z = 4 \n \nA) (1, 5, 7) \nB) (1, 1, 0) \nC) (1, 1, 1) \nD) (7, -1, -5) \nE) (5, 1, 5) \n \n \nQUESTÃO 12 – Determine a distância aproximada entre o ponto J(3, 1) e a reta  \ns : 6x – 2y + 11 = 0. \n \nA) 1,3 \nB) 2,6 \nC) 4,3 \nD) 12,1 \nE) 18,5 \n \n \nQUESTÃO 13 – Analise a seguinte proposição: "Existe pelo menos uma universidade em que todos \nos cursos têm, pelo menos, 100 alunos". A negação dessa proposição é logicamente equivalente à \nproposição: \n \nA) Em todas as universidades existe pelo menos um curso que possui, no máximo, 99 alunos. \nB) Em no máximo uma universidade existe um curso que possui, no máximo, 101 alunos. \nC) Há uma universidade em que existe pelo menos um curso com, no máximo, 99 alunos. \nD) Em cada universidade existe pelo menos um curso que possui, pelo menos, 100 alunos. \nE) Existe nenhuma universidade em que os cursos possuam, no máximo, 100 alunos. \n \n \nQUESTÃO 14 – Sendo p e q proposições simples, considere a proposição composta E(p,q), cujos \nvalores lógicos estão na tabela verdade a seguir: \n \np \nq \nE(p,q) \nF \nF \nV \nF \nV \nV \nV \nF \nF \nV \nV \nV \n \nQual é o valor da expressão E? \n \nA) P–>q \nB) p ou q \nC) q–>p \nD) p ou ~q \nE) (~p)→(p ou q) \n \n \nQUESTÃO 15 – A expressão lógica p→q é equivalente a: \n \nA) ~p∧~q \nB) ~p→q \nC) p→~q \nD) ~q->~p \nE) q→p \n \n \n',
 '761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 16 – Utilizando as leis de Morgan, obtenha uma expressão em forma de somas de \nprodutos para a seguinte função: \n \n𝐹= (𝑥+ 𝑦)(𝑥𝑦̅ + 𝑧)\n̅̅̅̅̅̅̅̅̅̅̅\n̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅ \n \nA) 𝑥̅ + 𝑥̅𝑧+ 𝑦 \nB)  𝑥𝑦\n̅̅̅ + 𝑥̅𝑦+ 𝑦 \nC) 𝑥̅𝑦+ 𝑥̅𝑦+ 𝑧 \nD) 𝑦̅ + 𝑧 \nE) 𝑥𝑦\n̅̅̅ + 𝑥̅𝑦 \n \n \nQUESTÃO 17 – A partir do seguinte circuito, apresentado na Figura 1, obtenha a equação de saída \nem soma de produtos (simplifique por álgebra de Boole). \n \n \nFigura 1 \n \nA) 𝑍= 𝐴𝐵̅ + 𝐴𝐵\n̅̅̅̅ + 𝐵𝐶 \nB) 𝑍=  𝐴𝐵̅ + 𝐵𝐶 \nC) 𝑍=  𝐴𝐵+ 𝐵𝐶\n̅̅̅̅ \nD) 𝑍=  𝐴𝐵̅ + 𝐴𝐵  \nE) 𝑍= 𝐴𝐵\n̅̅̅̅ + 𝐵 \n \n \nQUESTÃO 18 – Usando os conjuntos de dados A = {1, 4, 2, 6, 8, 10}, B = {1, 4, 6, 10},  \nC = {6, 4, 1, 10}, D = {6, 4, 1}, qual das seguintes alternativas é INCORRETA? \n \nA) A ⊆ B \nB) D ⊆ A \nC) B = C \nD) B ⊆ A \nE) A ≠ B \n \n \nQUESTÃO 19 – Com base na Tabela 1, calcule a média da seguinte amostra de número de filhos \nque têm as famílias que participaram da enquete: \n \nNº filho (Xi) \n0 1 2 3 4 \nNº famílias (ni) \n5 6 8 4 2 \nTabela 1 \n \nA) 1,12 \nB) 1,68 \nC) 2,11 \nD) 2,87 \nE) 3,21 \n \n \n \n \n \n',
 '761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 20 – Em uma linha de produção, sabe-se que a probabilidade de ter uma peça com \ndefeito é de 0,05. Se o conjunto de unidades determinadas constitui um conjunto de ensaios \nindependentes, qual é a probabilidade de que pelo menos uma peça se encontre com defeito em um \ntotal de 10 unidades? \n \nA) 10,0% \nB) 40,0% \nC) 50,0% \nD) 80,0% \nE) 100,0% \n \nFUNDAMENTOS DA COMPUTAÇÃO \n \nQUESTÃO 21 – Sobre os conceitos de complexidade de algoritmos, é correto afirmar que: \n \nA) O espaço requerido por um algoritmo sobre uma dada entrada pode ser medido pelo número de \nexecuções de algumas operações.  \nB) A complexidade de tempo usa como medida de desempenho a quantidade de memória necessária \npara a execução do algoritmo. \nC) A complexidade média é definida pelo crescimento da complexidade para entradas \nsuficientemente grandes.  \nD) A complexidade assintótica dá o valor esperado: a média dos esforços, levando em conta a \nprobabilidade de ocorrência de cada entrada. \nE) A complexidade pessimista de um algoritmo fornece seu desempenho no pior caso: o pior \ndesempenho que se pode esperar. Aqui, pode-se considerar os desempenhos sobre todas as \nentradas com tamanho n.  \n \n \nQUESTÃO 22 – Qual das seguintes afirmações é verdadeira sobre a análise de algoritmos \nrecursivos? \n \nA) A complexidade de tempo de um algoritmo recursivo é sempre mais rápida do que a de um \nalgoritmo iterativo equivalente. \nB) A complexidade de espaço de um algoritmo recursivo é sempre menor do que a de um algoritmo \niterativo equivalente. \nC) A análise de complexidade de um algoritmo recursivo é sempre mais fácil do que a de um \nalgoritmo iterativo equivalente. \nD) Algoritmos recursivos nunca podem sofrer de problemas de estouro de pilha (stack overflow). \nE) A escolha adequada da estrutura de dados pode reduzir o tempo e o espaço necessários para a \nexecução de algoritmos recursivos. \n \n \nQUESTÃO 23 – Considere o seguinte trecho de código: \n \nfor (i = 1; i <= n; i++) { \n    for (j = 1; j <= m; j++) { \n        // instruções O(1) \n    } \n} \n \nQual das seguintes afirmações é verdadeira sobre a complexidade assintótica desse trecho de \ncódigo? \n \nA) A complexidade é O(n) se m for uma constante, e O(m) se n for uma constante. \nB) A complexidade é O(n log m) se m for uma constante, e O(m log n) se n for uma constante. \nC) A complexidade é O(n + m) se n e m forem do mesmo tamanho. \nD) A complexidade é O(1) em todos os casos. \nE) A complexidade é O(nm) em todos os casos. \n \n \n \n \n',
 '761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 24 – Sobre funções Hash, é correto afirmar que: \n \nA) O método de divisão funciona em duas etapas. Na primeira etapa, multiplica-se a chave k por \numa constante A na faixa 0<A<1 e extrai-se a parte fracionária de kA. Na segunda etapa, \nmultiplica-se esse valor por m e toma-se o piso do resultado.  \nB) Em endereçamento aberto, todos os elementos ficam na própria tabela de espelhamento. Isto é, \ncada entrada da tabela contém um elemento do conjunto dinâmico ou NIL. Ao procurar um \nelemento, examina-se sistematicamente as posições da tabela até encontrar o elemento desejado \nou até confirmar que o elemento não está na tabela.  \nC) No método de encadeamento não existe nenhuma lista e nenhum elemento fora da tabela.  \nD) O hashing pode proporcionar excelente desempenho no pior caso, quando o conjunto de chaves \né dinâmico, isto é, assim que as chaves são armazenadas na tabela, o conjunto de chaves muda \nautomaticamente de tempos em tempos.  \nE) No método de multiplicação, mapeia-se uma chave k para uma de m posições, tomando o resto \nda divisão de k por m.  \n \n \nQUESTÃO 25 – Sobre as árvores binárias de busca, é correto afirmar que: \n \nA) Seja x um nó em uma árvore de busca binária. Se y é um nó na subárvore esquerda de x, então \ny.chave \uf0b3 x.chave. Se y é um nó na subárvore direita de x, então x.chave \uf0a3  y.chave. \nB) A propriedade de árvore de busca que permite imprimir todas as chaves em sequência ordenada \npor meio de um simples algoritmo recursivo é denominada percurso de árvore em pré-ordem.  \nC) Para excluir um nó z de uma árvore de busca binária T, se z tem apenas um filho, então \nsimplesmente o removemos modificando seu pai de modo a substituir z por NIL como seu filho.   \nD) Para excluir um nó z de uma árvore de busca binária T, se z tem dois filhos, então elevamos o \nprimeiro filho para que ocupe a posição de z na árvore modificando o pai de z de modo a substituir \nz pelo filho de z.  \nE) Para encontrar um nó em uma árvore de busca binária cuja chave é um mínimo, deve-se seguir \nos ponteiros de filhos da esquerda desde a raiz até encontrar um valor NIL.  \n \n \nQUESTÃO 26 – A ordenação ________________ determina, para cada elemento de entrada x, o \nnúmero de elementos menores que x e usa essa informação para inserir o elemento x diretamente \nem sua posição no arranjo de saída. Por exemplo, se 17 elementos forem menores que x, então x \npertence à posição de saída 18.  \n \nAssinale a alternativa que preenche corretamente a lacuna do trecho acima.  \n \nA) mergesort \nB) quicksort \nC) por contagem \nD) por fila de prioridade \nE) por intercalação com sentinela \n \n \nQUESTÃO 27 – Quais são os valores em decimal do binário (8 bits) 10011001, considerando a \nrepresentação sem sinal e em complemento de 2, respectivamente? \n \nA) 153, -102 \nB) 100, -101 \nC) 153, -103 \nD) 129, 103 \nE) 1, -1 \n \n \n \n \n \n \n \n',
 '761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 28 – Qual é o resultado da seguinte fórmula Infixo A+B*(C-D*(E-F)-G*H)-I*3 convertida \npara a notação polonesa? \n \nA) A+*(B*(C-(D*(E-(F-G*H-I*3))))) \nB) A+B*C-D*E-F-G*H-I*3+*-*-*-*+ \nC) +*-*--*A -*ABCDEFGHI3 \nD) ABCDEF-*-GH*-*+I3*- \nE) ABCDEFGHI3+*-*-*-*- \n \n \nQUESTÃO 29 – O computador tem um tempo de acesso à memória principal de 60 ns. Queremos \nreduzir esse tempo para 20 ns adicionando no cache. Qual a velocidade do cache (tempo de acesso) \nse pudermos esperar uma probabilidade de 90% de acerto? \n \nA) 04 ns. \nB) 14 ns. \nC) 24 ns. \nD) 54 ns. \nE) 84 ns. \n \n \nQUESTÃO 30 – Considere um sistema numérico binário com 8 bits e o uso do complemento de 2 \npara representação de números inteiros para a realização da operação 4910 −12010. Com base nisso, \nanalise as assertivas abaixo, assinalando V, se verdadeiras, ou F, se falsas. \n \n(  ) O sistema numérico com essas características pode representar valores entre +255 e -256. \n(  ) O resultado da operação será representado pelo valor 101110012. \n(  ) Há um estouro de registro nessa operação quando feita nesse sistema. \n(  ) A operação de subtração é realizada ao somar a representação de complemento de 2 de 12010 \ncom a representação binária de 4910. \n \nA ordem correta de preenchimento dos parênteses, de cima para baixo, é: \n \nA) V – F – F – V. \nB) V – V – F – F. \nC) V – F – V – F. \nD) F – F – V – V. \nE) F – V – F – V. \n \n \nQUESTÃO 31 – Considere um circuito sequencial composto por um flip-flop JK e dois flip-flops. Para \nfins de simplicidade, o sinal de clock (CLK) está omitido, porém assuma que todos os componentes \nestão sincronizados nele. O diagrama do circuito é apresentado na Figura 2 abaixo: \n \nFigura 2 \n \nDado o estado inicial 𝑄0 = 𝑄1 = 𝑄2 = 1, informe quantas vezes o sinal será resetado (ou seja, será \nmudado para zero) depois de 6 ciclos de clock, sendo 𝐴= 𝐵= 1: \n \nA) 0 \nB) 1 \nC) 2 \nD) 3 \nE) 4 \n \n \n \n',
 '761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 32 – Considere o circuito combinacional composto por portas lógicas NOT, AND e XOR, \nalém de um multiplexador, conforme a Figura 3, e analise as assertivas abaixo: \n \n \nFigura 3 \n \nI. A expressão (𝐴𝐵+ 𝐴𝐵) ∙𝐶 representa a função booleana que define o valor de S. \nII. A expressão 𝐵⊗𝐴⊕𝐶 representa a função booleana que define o valor de T. \nIII. O circuito contém a função de um somador binário completo, com entrada de sinais de dois \noperandos e do transporte, e saída do sinal de soma e do transporte. \n \nQuais estão corretas? \n \nA) Apenas I. \nB) Apenas II. \nC) Apenas III. \nD) Apenas I e III. \nE) I, II e III. \n \n \nQUESTÃO 33 – Considere o seguinte código em Linguagem C (Compilador Ansi C):  \n \n  int a = 2, b = 4, c = -1; \n  int *ptx, *pty, *ptz; \n  ptx = &a; \n  pty = &b; \n  ptz = &c; \n   \n  printf ("%d %d %d %d %d %d \\n", a, b, c, *ptx, *pty, *ptz); \n  a = (*ptx) * (*pty); \n  b = *ptz + 1; \n  ++c; \n  printf ("%d %d %d %d %d %d \\n", a, b, c, *ptx, *pty, *ptz); \n \nAssinale a alternativa que corresponde à saída na tela. \n \nA) 2  2 -1 2 4 -1 \n8 -1  0 8 0  0 \n \nB) 2 4 -1 2 2 -1 \n2 0 -1 2 0 -1 \n \nC) 2 2 -1 2 4  0 \n8 0 -1 8 0 -1 \n \nD) 2 4 -1 2 4 -1 \n8 0 -1 8 0 -1 \n \nE) 2 4 -1 2 4 -1 \n8 0  0 8 0  0 \n',
 '761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 34 – Considerando o diagrama de classes UML representado na Figura 4, assinale a \nalternativa correta. \n \n \nFigura 4 \n \nA) A classe “Pessoa” se associa com a classe “Funcionario”, que por sua vez tem uma relação de \ngeneralização com a classe “Tarefa”. \nB) A classe “Pessoa” herda da classe “Funcionario”, que tem uma relação de associação com a classe \n“Tarefa”. \nC) A associação com navegabilidade da classe “Funcionario” para a classe “Tarefa” gera no código \num atributo “lista de objetos” da classe “Tarefa” na classe “Funcionario”. \nD) A classe “Tarefa” faz parte da classe “Funcionario”, constituindo uma relação de agregação. \nE) O método “addTarefa(tarefa: Tarefa)” pode ser invocado a partir de uma instância da classe \n“Pessoa”, através de polimorfismo. \n \n \nQUESTÃO 35 – Relacione a Coluna 1 à Coluna 2, associando cada Paradigma de Linguagem de \nProgramação à sua respectiva Linguagem de Programação. \n \nColuna 1 \n1. Programação Procedural. \n2. Programação Funcional. \n3. Programação de Tipos Abstratos de Dados. \n4. Programação Orientada a Objetos. \n5. Programação Declarativa. \n \nColuna 2 \n(  ) CLIPS. \n(  ) Smalltalk. \n(  ) CLU. \n(  ) C. \n(  ) LISP. \n \nA ordem correta de preenchimento dos parênteses, de cima para baixo, é: \n \nA) 1 – 2 – 3 – 4 – 5. \nB) 2 – 3 – 4 – 5 – 1. \nC) 3 – 4 – 5 – 1 – 2. \nD) 4 – 5 – 3 – 2 – 1. \nE) 5 – 4 – 3 – 1 – 2. \n \n \n \n \n \n \n \n \n \n \n',
 '761_POSCOMP_NS_DM \nExecução: Fundatec \nEXAME POSCOMP 2023 \n15/9/202313:07:48 \nQUESTÃO 36 – Qual máquina de aceitação já seria capaz de reconhecer a linguagem a seguir? \n \n𝐿= {𝑤∈{𝑎, 𝑏}∗ | 𝑤 𝑐𝑜𝑛𝑡é𝑚 𝑎 𝑚𝑒𝑠𝑚𝑎 𝑞𝑢𝑎𝑛𝑡𝑖𝑑𝑎𝑑𝑒 𝑑𝑒 𝑎′𝑠 𝑒 𝑏′𝑠} \n \nA) Autômato Finito. \nB) Autômato com Pilha Determinístico. \nC) Autômato com Pilha Não Determinístico. \nD) Máquina de Turing Decididora. \nE) Máquina de Turing Reconhecedora. \n \n \nQUESTÃO 37 – Qual é a Expressão Regular (ER) que denota a linguagem a seguir? \n \n𝐿= {𝑤∈{𝑎, 𝑏}∗ | 𝑤 𝑛ã𝑜 𝑝𝑜𝑑𝑒 𝑡𝑒𝑟𝑚𝑖𝑛𝑎𝑟 𝑐𝑜𝑚 𝑏𝑎} \n \nA) ¬( (𝑎∪𝑏)∗𝑏𝑎 ) \nB) (𝑎∪𝑏)∗𝑏𝑎 \nC) (𝑎∪𝑏)∗−( (𝑎∪𝑏)∗𝑏𝑎 ) \nD) ( (𝑎∪𝑏)∗(𝑏∪𝑎𝑎) ) ∪𝑎∪𝜆 \nE) A linguagem L não é regular e, portanto, não pode ser denotada por uma ER. \n \n \nQUESTÃO 38 – Dada a linguagem 𝐿= {𝑤∈{𝑎, 𝑏}∗ | 𝑜 𝑡𝑒𝑟𝑐𝑒𝑖𝑟𝑜 ú𝑙𝑡𝑖𝑚𝑜 𝑠í𝑚𝑏𝑜𝑙𝑜 𝑑𝑒 𝑤 é 𝑎}, analise as \nassertivas abaixo, assinalando V, se verdadeiras, ou F, se falsas. \n \n(  ) O menor Autômato Finito Não Determinístico (AFND) que reconhece L tem 4 (quatro) estados. \n(  ) O Autômato Finito Determinístico (AFD) que reconhece L tem, no mínimo, 8 (oito) estados. \n(  ) A menor Gramática Regular (GR) que gera L tem 3 (três) não terminais. \n(  ) O conjunto regular {𝑎, 𝑏}∗{𝑎}{𝑎, 𝑏}{𝑎, 𝑏} denota L. \n \nA ordem correta de preenchimento dos parênteses, de cima para baixo, é: \n \nA) F – F – V – V.  \nB) V – V – V – V.  \nC) F – V – F – V.  \nD) V – V – F – F.  \nE) V – F – V – F. \n \n \nQUESTÃO 39 – Nos arquivos ordenados, os registros são dispostos fisicamente no disco de acordo \ncom os valores de um de seus campos: o campo de ordenação (chave). Analise as seguintes \nassertivas sobre arquivos ordenados: \n \nI. A leitura dos registros na ordem dos valores da chave de ordenação é mais eficiente se \ncomparada à leitura desses registros em arquivos heap. \nII. Permite atender de forma eficiente condições de pesquisa sobre o campo de ordenação no \nformato <chave = valor> ou condição de intervalo (isto é, a chave estar no intervalo entre o \nvalor1 e valor2).   \nIII. Para acelerar o acesso a um registro baseado no valor de uma chave em arquivos ordenados, a \nmelhor técnica de pesquisa é a técnica de hash. \n \nQuais estão corretas? \n \nA) Apenas I. \nB) Apenas II. \nC) Apenas III. \nD) Apenas I e II. \nE) I, II e III. \n \n',

In [14]:
import re

In [15]:
import re

def separar_pergunta_opcoes(bloco_questao):
    """
    Processa um bloco individual de questão separando pergunta e opções
    
    Args:
        bloco_questao (str): Texto contendo uma questão completa
        
    Returns:
        dict: Dicionário com 'numero', 'pergunta' e 'opcoes'
    """
    # Padrão para capturar o número da questão e a pergunta (incluindo múltiplas linhas)
    padrao_numero = re.compile(
        r'^QUESTÃO (\d+) – (.*?)(?=\n\s*[A-E]\))',
        re.DOTALL
    )
    match = padrao_numero.search(bloco_questao)
    
    if not match:
        return None
    
    numero = match.group(1)
    pergunta = match.group(2).strip()
    
    # Captura todas as opções (incluindo múltiplas linhas)
    padrao_opcoes = re.compile(
        r'([A-E]\)\s+.*?(?=\n[A-E]\)|\Z))',
        re.DOTALL
    )
    opcoes = padrao_opcoes.findall(bloco_questao)
    
    # Limpeza das opções: remove quebras de linha e espaços extras
    opcoes = [re.sub(r'\s+', ' ', opcao.strip()) for opcao in opcoes]
    
    return {
        'numero': numero,
        'pergunta': pergunta,
        'opcoes': opcoes
    }

def processar_textos_completos(lista_textos):
    """
    Processa uma lista de textos com múltiplas questões
    
    Args:
        lista_textos (list): Lista contendo textos com várias questões
        
    Returns:
        list: Lista de dicionários com questões processadas
    """
    todas_questoes = []
    
    for texto in lista_textos:
        # Divide o texto em blocos de questões usando "QUESTÃO" como marcador
        blocos_questoes = re.split(r'\n(?=QUESTÃO \d+)', texto.strip())
        
        for bloco in blocos_questoes:
            bloco = bloco.strip()
            if not bloco:
                continue
            questao = separar_pergunta_opcoes(bloco)
            if questao:
                todas_questoes.append(questao)
    
    return todas_questoes

In [16]:
# def separar_pergunta_opcoes(bloco_questao):
#     """
#     Processa um bloco individual de questão separando pergunta e opções.
    
#     Args:
#         bloco_questao (str): Texto contendo uma questão completa.
        
#     Returns:
#         dict: Dicionário com 'numero', 'pergunta' e 'opcoes'.
#     """
#     # Captura número da questão e a pergunta
#     padrao_numero_pergunta = r"^(\d+)\n(.+?)(?=\n\(A\))"
#     match = re.search(padrao_numero_pergunta, bloco_questao, re.DOTALL)
    
#     if not match:
#         return None
    
#     numero = match.group(1)
#     pergunta = match.group(2).strip()
    
#     # Captura todas as opções (A, B, C, D) e mantém o formato correto
#     padrao_opcoes = r"\((A|B|C|D)\)\s+(.*?)(?=\n\(A\)|\n\(B\)|\n\(C\)|\n\(D\)|$)"
#     opcoes = re.findall(padrao_opcoes, bloco_questao, re.DOTALL)
    
#     # Formata as opções corretamente
#     opcoes_formatadas = [f"{letra}) {texto.strip()}" for letra, texto in opcoes]
    
#     return {
#         'numero': numero,
#         'pergunta': pergunta,
#         'opcoes': opcoes_formatadas
#     }

# def processar_textos_completos(lista_textos):
#     """
#     Processa uma lista de textos com múltiplas questões.
    
#     Args:
#         lista_textos (list): Lista contendo textos com várias questões.
        
#     Returns:
#         list: Lista de dicionários com questões processadas.
#     """
#     todas_questoes = []
    
#     for texto in lista_textos:
#         # Divide cada questão com base em números no início da linha
#         blocos_questoes = re.split(r"\n(?=\d+\n)", texto.strip())
        
#         for bloco in blocos_questoes:
#             questao = separar_pergunta_opcoes(bloco)
#             if questao:
#                 todas_questoes.append(questao)
    
#     return todas_questoes

In [17]:
# Processamento
questoes = processar_textos_completos(texto_questoes)

# Exibindo os resultados
for questao in questoes:
    print(f"\nQUESTÃO {questao['numero']}:")
    print(questao['pergunta'])
    print("\nOPÇÕES:")
    for opcao in questao['opcoes']:
        print(opcao)
    print("-" * 50)

QUESTÃO 01:
Utilize o método de Eliminação de Gauss para resolver o sistema a seguir:

-3x + y + z = 1
x – 2y + z = 4
-x + y − 3z = -7

OPÇÕES:
A) (0, -1, 2)
B) (0, 1, 0)
C) (2, 0, 2)
D) (2, 1, 2)
E) (-1, -1, -1)
--------------------------------------------------

QUESTÃO 02:
Determine o valor de x para que o vetor (1, x, 5) ∈ R3 pertença ao subespaço
<(1, 2, 3), (1, 1, 1)>

OPÇÕES:
A) x = 0
B) x = -1
C) x = 1
D) x = 3
E) x = 7
--------------------------------------------------

QUESTÃO 03:
Determine o polinômio característico de J:

J = (
2
−2
1
1
−1
1
1
−2
2
)

OPÇÕES:
A) 0
B) x
C) (1 − x)
D) (1 − x)²
E) (1 − x)³
--------------------------------------------------

QUESTÃO 04:
Nos jogos da Mega-Sena, são sorteados a cada concurso 6 números no intervalo de
1 a 60. Leva o prêmio quem acertar os 6 números sorteados. O apostador, ao fazer um jogo, pode
optar por preencher um bilhete com 6, 7, 8 ou 9 números escolhidos. Se o apostador registra um
bilhete com 8 números escolhidos, quantos bilhetes de 6 números ele faria com os mesmos
8 números escolhidos?

OPÇÕES:
A) 56
B) 8!
C) 6!
D) 28
E) 72
--------------------------------------------------

QUESTÃO 05:
Recentemente, com a pandemia de Covid-19, houve grande interesse em
determinar conjuntos de regiões (de países, estados, municípios, etc.) com alta incidência da doença,
com o objetivo de determinar políticas de mitigação da doença nesses locais. Nesse sentido, dado
um mapa subdividido em regiões, um cluster é definido como sendo um subconjunto de regiões
desse mapa (nesse caso, pode ser formado por regiões que não fazem fronteira entre si). Qual o
número de possíveis clusters para um mapa com 10 regiões?

OPÇÕES:
A) 1024
B) 10
C) 100
D) 512
E) 20
--------------------------------------------------

QUESTÃO 06:
Um anagrama é uma nova palavra formada pela permutação de letras de uma
palavra. Essa nova palavra não precisa fazer sentido. Um anagrama de POSCOMP, por exemplo, seria
MOCPSOP. Quantos são os anagramas da palavra POSCOMP?

OPÇÕES:
A) 126
B) 252
C) 1260
D) 2520
E) 5040
--------------------------------------------------

QUESTÃO 07:
Calcule o lim
𝑥→10−3 𝑙𝑜𝑔(10 ∙𝑥).

OPÇÕES:
A) 0
B) -3
C) -2
D) 1
E) 100
--------------------------------------------------

QUESTÃO 08:
Determine os intervalos da função 𝑓(𝑥) = 5𝑥²√𝑥+ 1.

OPÇÕES:
A) 𝐼1 = (−1, − 4 5) ; 𝐼2 = (− 4 5 , 0); 𝐼3 = (0, ∞)
B) 𝐼1 = (−∞, − 4 5) ; 𝐼2 = (− 4 5 , 0) ; 𝐼3 = (0, ∞)
C) 𝐼1 = (−1, 0); 𝐼2 = (0, 1); 𝐼3 = (1, ∞)
D) 𝐼1 = (−1, 1); 𝐼2 = (1, 5 4) ; 𝐼3 = ( 5 4 , ∞)
E) 𝐼1 = (−∞, −1); 𝐼2 = (−1, 1); 𝐼3 = (1, ∞)
--------------------------------------------------

QUESTÃO 09:
Calcule o vetor gradiente da função 𝑓(𝑥, 𝑦) = 𝑒−𝑥𝑠𝑒𝑛(𝑥+ 𝑦) no ponto 𝑃 (0, 𝜋).

OPÇÕES:
A) ∇𝑓(0, 𝜋) = (0 1)
B) ∇𝑓(0, 𝜋) = (1 1)
C) ∇𝑓(0, 𝜋) = (−1 1 )
D) ∇𝑓(0, 𝜋) = (−1 −1)
E) ∇𝑓(0, 𝜋) = (0 0)
--------------------------------------------------

QUESTÃO 10:
Dados os vetores u(3, 3, 2), v(5, -2, 1) e w(1, -1, 0), calcule a e b tal que
u = av + bw.

OPÇÕES:
A) a = 2 e b = -7
B) a = -1 e b = 5
C) a = 5 e b = -3
D) a = 3 e b = -9
E) a = -6 e b = 1
--------------------------------------------------

QUESTÃO 11:
Calcule o vetor diretor da interseção dos seguintes planos:

x + 2y + z = 3
2x – y +3z = 4

OPÇÕES:
A) (1, 5, 7)
B) (1, 1, 0)
C) (1, 1, 1)
D) (7, -1, -5)
E) (5, 1, 5)
--------------------------------------------------

QUESTÃO 12:
Determine a distância aproximada entre o ponto J(3, 1) e a reta
s : 6x – 2y + 11 = 0.

OPÇÕES:
A) 1,3
B) 2,6
C) 4,3
D) 12,1
E) 18,5
--------------------------------------------------

QUESTÃO 13:
Analise a seguinte proposição: "Existe pelo menos uma universidade em que todos
os cursos têm, pelo menos, 100 alunos". A negação dessa proposição é logicamente equivalente à
proposição:

OPÇÕES:
A) Em todas as universidades existe pelo menos um curso que possui, no máximo, 99 alunos.
B) Em no máximo uma universidade existe um curso que possui, no máximo, 101 alunos.
C) Há uma universidade em que existe pelo menos um curso com, no máximo, 99 alunos.
D) Em cada universidade existe pelo menos um curso que possui, pelo menos, 100 alunos.
E) Existe nenhuma universidade em que os cursos possuam, no máximo, 100 alunos.
--------------------------------------------------

QUESTÃO 14:
Sendo p e q proposições simples, considere a proposição composta E(p,q), cujos
valores lógicos estão na tabela verdade a seguir:

p
q
E(p,q)
F
F
V
F
V
V
V
F
F
V
V
V

Qual é o valor da expressão E?

OPÇÕES:
A) P–>q
B) p ou q
C) q–>p
D) p ou ~q
E) (~p)→(p ou q)
--------------------------------------------------

QUESTÃO 15:
A expressão lógica p→q é equivalente a:

OPÇÕES:
A) ~p∧~q
B) ~p→q
C) p→~q
D) ~q->~p
E) q→p
--------------------------------------------------

QUESTÃO 16:
Utilizando as leis de Morgan, obtenha uma expressão em forma de somas de
produtos para a seguinte função:

𝐹= (𝑥+ 𝑦)(𝑥𝑦̅ + 𝑧)
̅̅̅̅̅̅̅̅̅̅̅
̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅̅

OPÇÕES:
A) 𝑥̅ + 𝑥̅𝑧+ 𝑦
B) 𝑥𝑦 ̅̅̅ + 𝑥̅𝑦+ 𝑦
C) 𝑥̅𝑦+ 𝑥̅𝑦+ 𝑧
D) 𝑦̅ + 𝑧
E) 𝑥𝑦 ̅̅̅ + 𝑥̅𝑦
--------------------------------------------------

QUESTÃO 17:
A partir do seguinte circuito, apresentado na Figura 1, obtenha a equação de saída
em soma de produtos (simplifique por álgebra de Boole).


Figura 1

OPÇÕES:
A) 𝑍= 𝐴𝐵̅ + 𝐴𝐵 ̅̅̅̅ + 𝐵𝐶
B) 𝑍= 𝐴𝐵̅ + 𝐵𝐶
C) 𝑍= 𝐴𝐵+ 𝐵𝐶 ̅̅̅̅
D) 𝑍= 𝐴𝐵̅ + 𝐴𝐵
E) 𝑍= 𝐴𝐵 ̅̅̅̅ + 𝐵
--------------------------------------------------

QUESTÃO 18:
Usando os conjuntos de dados A = {1, 4, 2, 6, 8, 10}, B = {1, 4, 6, 10},
C = {6, 4, 1, 10}, D = {6, 4, 1}, qual das seguintes alternativas é INCORRETA?

OPÇÕES:
A) A ⊆ B
B) D ⊆ A
C) B = C
D) B ⊆ A
E) A ≠ B
--------------------------------------------------

QUESTÃO 19:
Com base na Tabela 1, calcule a média da seguinte amostra de número de filhos
que têm as famílias que participaram da enquete:

Nº filho (Xi)
0 1 2 3 4
Nº famílias (ni)
5 6 8 4 2
Tabela 1

OPÇÕES:
A) 1,12
B) 1,68
C) 2,11
D) 2,87
E) 3,21
--------------------------------------------------

QUESTÃO 20:
Em uma linha de produção, sabe-se que a probabilidade de ter uma peça com
defeito é de 0,05. Se o conjunto de unidades determinadas constitui um conjunto de ensaios
independentes, qual é a probabilidade de que pelo menos uma peça se encontre com defeito em um
total de 10 unidades?

OPÇÕES:
A) 10,0%
B) 40,0%
C) 50,0%
D) 80,0%
E) 100,0% FUNDAMENTOS DA COMPUTAÇÃO
--------------------------------------------------

QUESTÃO 21:
Sobre os conceitos de complexidade de algoritmos, é correto afirmar que:

OPÇÕES:
A) O espaço requerido por um algoritmo sobre uma dada entrada pode ser medido pelo número de execuções de algumas operações.
B) A complexidade de tempo usa como medida de desempenho a quantidade de memória necessária para a execução do algoritmo.
C) A complexidade média é definida pelo crescimento da complexidade para entradas suficientemente grandes.
D) A complexidade assintótica dá o valor esperado: a média dos esforços, levando em conta a probabilidade de ocorrência de cada entrada.
E) A complexidade pessimista de um algoritmo fornece seu desempenho no pior caso: o pior desempenho que se pode esperar. Aqui, pode-se considerar os desempenhos sobre todas as entradas com tamanho n.
--------------------------------------------------

QUESTÃO 22:
Qual das seguintes afirmações é verdadeira sobre a análise de algoritmos
recursivos?

OPÇÕES:
A) A complexidade de tempo de um algoritmo recursivo é sempre mais rápida do que a de um algoritmo iterativo equivalente.
B) A complexidade de espaço de um algoritmo recursivo é sempre menor do que a de um algoritmo iterativo equivalente.
C) A análise de complexidade de um algoritmo recursivo é sempre mais fácil do que a de um algoritmo iterativo equivalente.
D) Algoritmos recursivos nunca podem sofrer de problemas de estouro de pilha (stack overflow).
E) A escolha adequada da estrutura de dados pode reduzir o tempo e o espaço necessários para a execução de algoritmos recursivos.
--------------------------------------------------

QUESTÃO 23:
Considere o seguinte trecho de código:

for (i = 1; i <= n; i++) {
    for (j = 1; j <= m; j++) {
        // instruções O(1)
    }
}

Qual das seguintes afirmações é verdadeira sobre a complexidade assintótica desse trecho de
código?

OPÇÕES:
A) A complexidade é O(n) se m for uma constante, e O(m) se n for uma constante.
B) A complexidade é O(n log m) se m for uma constante, e O(m log n) se n for uma constante.
C) A complexidade é O(n + m) se n e m forem do mesmo tamanho.
D) A complexidade é O(1) em todos os casos.
E) A complexidade é O(nm) em todos os casos.
--------------------------------------------------

QUESTÃO 24:
Sobre funções Hash, é correto afirmar que:

OPÇÕES:
A) O método de divisão funciona em duas etapas. Na primeira etapa, multiplica-se a chave k por uma constante A na faixa 0<A<1 e extrai-se a parte fracionária de kA. Na segunda etapa, multiplica-se esse valor por m e toma-se o piso do resultado.
B) Em endereçamento aberto, todos os elementos ficam na própria tabela de espelhamento. Isto é, cada entrada da tabela contém um elemento do conjunto dinâmico ou NIL. Ao procurar um elemento, examina-se sistematicamente as posições da tabela até encontrar o elemento desejado ou até confirmar que o elemento não está na tabela.
C) No método de encadeamento não existe nenhuma lista e nenhum elemento fora da tabela.
D) O hashing pode proporcionar excelente desempenho no pior caso, quando o conjunto de chaves é dinâmico, isto é, assim que as chaves são armazenadas na tabela, o conjunto de chaves muda automaticamente de tempos em tempos.
E) No método de multiplicação, mapeia-se uma chave k para uma de m posições, tomando o resto da divisão de k por m.
--------------------------------------------------

QUESTÃO 25:
Sobre as árvores binárias de busca, é correto afirmar que:

OPÇÕES:
A) Seja x um nó em uma árvore de busca binária. Se y é um nó na subárvore esquerda de x, então y.chave  x.chave. Se y é um nó na subárvore direita de x, então x.chave  y.chave.
B) A propriedade de árvore de busca que permite imprimir todas as chaves em sequência ordenada por meio de um simples algoritmo recursivo é denominada percurso de árvore em pré-ordem.
C) Para excluir um nó z de uma árvore de busca binária T, se z tem apenas um filho, então simplesmente o removemos modificando seu pai de modo a substituir z por NIL como seu filho.
D) Para excluir um nó z de uma árvore de busca binária T, se z tem dois filhos, então elevamos o primeiro filho para que ocupe a posição de z na árvore modificando o pai de z de modo a substituir z pelo filho de z.
E) Para encontrar um nó em uma árvore de busca binária cuja chave é um mínimo, deve-se seguir os ponteiros de filhos da esquerda desde a raiz até encontrar um valor NIL.
--------------------------------------------------

QUESTÃO 26:
A ordenação ________________ determina, para cada elemento de entrada x, o
número de elementos menores que x e usa essa informação para inserir o elemento x diretamente
em sua posição no arranjo de saída. Por exemplo, se 17 elementos forem menores que x, então x
pertence à posição de saída 18.

Assinale a alternativa que preenche corretamente a lacuna do trecho acima.

OPÇÕES:
A) mergesort
B) quicksort
C) por contagem
D) por fila de prioridade
E) por intercalação com sentinela
--------------------------------------------------

QUESTÃO 27:
Quais são os valores em decimal do binário (8 bits) 10011001, considerando a
representação sem sinal e em complemento de 2, respectivamente?

OPÇÕES:
A) 153, -102
B) 100, -101
C) 153, -103
D) 129, 103
E) 1, -1
--------------------------------------------------

QUESTÃO 28:
Qual é o resultado da seguinte fórmula Infixo A+B*(C-D*(E-F)-G*H)-I*3 convertida
para a notação polonesa?

OPÇÕES:
A) A+*(B*(C-(D*(E-(F-G*H-I*3)))))
B) A+B*C-D*E-F-G*H-I*3+*-*-*-*+
C) +*-*--*A -*ABCDEFGHI3
D) ABCDEF-*-GH*-*+I3*-
E) ABCDEFGHI3+*-*-*-*-
--------------------------------------------------

QUESTÃO 29:
O computador tem um tempo de acesso à memória principal de 60 ns. Queremos
reduzir esse tempo para 20 ns adicionando no cache. Qual a velocidade do cache (tempo de acesso)
se pudermos esperar uma probabilidade de 90% de acerto?

OPÇÕES:
A) 04 ns.
B) 14 ns.
C) 24 ns.
D) 54 ns.
E) 84 ns.
--------------------------------------------------

QUESTÃO 30:
Considere um sistema numérico binário com 8 bits e o uso do complemento de 2
para representação de números inteiros para a realização da operação 4910 −12010. Com base nisso,
analise as assertivas abaixo, assinalando V, se verdadeiras, ou F, se falsas.

(  ) O sistema numérico com essas características pode representar valores entre +255 e -256.
(  ) O resultado da operação será representado pelo valor 101110012.
(  ) Há um estouro de registro nessa operação quando feita nesse sistema.
(  ) A operação de subtração é realizada ao somar a representação de complemento de 2 de 12010
com a representação binária de 4910.

A ordem correta de preenchimento dos parênteses, de cima para baixo, é:

OPÇÕES:
A) V – F – F – V.
B) V – V – F – F.
C) V – F – V – F.
D) F – F – V – V.
E) F – V – F – V.
--------------------------------------------------

QUESTÃO 31:
Considere um circuito sequencial composto por um flip-flop JK e dois flip-flops. Para
fins de simplicidade, o sinal de clock (CLK) está omitido, porém assuma que todos os componentes
estão sincronizados nele. O diagrama do circuito é apresentado na Figura 2 abaixo:

Figura 2

Dado o estado inicial 𝑄0 = 𝑄1 = 𝑄2 = 1, informe quantas vezes o sinal será resetado (ou seja, será
mudado para zero) depois de 6 ciclos de clock, sendo 𝐴= 𝐵= 1:

OPÇÕES:
A) 0
B) 1
C) 2
D) 3
E) 4
--------------------------------------------------

QUESTÃO 32:
Considere o circuito combinacional composto por portas lógicas NOT, AND e XOR,
além de um multiplexador, conforme a Figura 3, e analise as assertivas abaixo:


Figura 3

I. A expressão (𝐴𝐵+ 𝐴𝐵) ∙𝐶 representa a função booleana que define o valor de S.
II. A expressão 𝐵⊗𝐴⊕𝐶 representa a função booleana que define o valor de T.
III. O circuito contém a função de um somador binário completo, com entrada de sinais de dois
operandos e do transporte, e saída do sinal de soma e do transporte.

Quais estão corretas?

OPÇÕES:
A) Apenas I.
B) Apenas II.
C) Apenas III.
D) Apenas I e III.
E) I, II e III.
--------------------------------------------------

QUESTÃO 33:
Considere o seguinte código em Linguagem C (Compilador Ansi C):

  int a = 2, b = 4, c = -1;
  int *ptx, *pty, *ptz;
  ptx = &a;
  pty = &b;
  ptz = &c;

  printf ("%d %d %d %d %d %d \n", a, b, c, *ptx, *pty, *ptz);
  a = (*ptx) * (*pty);
  b = *ptz + 1;
  ++c;
  printf ("%d %d %d %d %d %d \n", a, b, c, *ptx, *pty, *ptz);

Assinale a alternativa que corresponde à saída na tela.

OPÇÕES:
A) 2 2 -1 2 4 -1 8 -1 0 8 0 0
B) 2 4 -1 2 2 -1 2 0 -1 2 0 -1
C) 2 2 -1 2 4 0 8 0 -1 8 0 -1
D) 2 4 -1 2 4 -1 8 0 -1 8 0 -1
E) 2 4 -1 2 4 -1 8 0 0 8 0 0
--------------------------------------------------

QUESTÃO 34:
Considerando o diagrama de classes UML representado na Figura 4, assinale a
alternativa correta.


Figura 4

OPÇÕES:
A) A classe “Pessoa” se associa com a classe “Funcionario”, que por sua vez tem uma relação de generalização com a classe “Tarefa”.
B) A classe “Pessoa” herda da classe “Funcionario”, que tem uma relação de associação com a classe “Tarefa”.
C) A associação com navegabilidade da classe “Funcionario” para a classe “Tarefa” gera no código um atributo “lista de objetos” da classe “Tarefa” na classe “Funcionario”.
D) A classe “Tarefa” faz parte da classe “Funcionario”, constituindo uma relação de agregação.
E) O método “addTarefa(tarefa: Tarefa)” pode ser invocado a partir de uma instância da classe “Pessoa”, através de polimorfismo.
--------------------------------------------------

QUESTÃO 35:
Relacione a Coluna 1 à Coluna 2, associando cada Paradigma de Linguagem de
Programação à sua respectiva Linguagem de Programação.

Coluna 1
1. Programação Procedural.
2. Programação Funcional.
3. Programação de Tipos Abstratos de Dados.
4. Programação Orientada a Objetos.
5. Programação Declarativa.

Coluna 2
(  ) CLIPS.
(  ) Smalltalk.
(  ) CLU.
(  ) C.
(  ) LISP.

A ordem correta de preenchimento dos parênteses, de cima para baixo, é:

OPÇÕES:
A) 1 – 2 – 3 – 4 – 5.
B) 2 – 3 – 4 – 5 – 1.
C) 3 – 4 – 5 – 1 – 2.
D) 4 – 5 – 3 – 2 – 1.
E) 5 – 4 – 3 – 1 – 2.
--------------------------------------------------

QUESTÃO 36:
Qual máquina de aceitação já seria capaz de reconhecer a linguagem a seguir?

𝐿= {𝑤∈{𝑎, 𝑏}∗ | 𝑤 𝑐𝑜𝑛𝑡é𝑚 𝑎 𝑚𝑒𝑠𝑚𝑎 𝑞𝑢𝑎𝑛𝑡𝑖𝑑𝑎𝑑𝑒 𝑑𝑒 𝑎′𝑠 𝑒 𝑏′𝑠}

OPÇÕES:
A) Autômato Finito.
B) Autômato com Pilha Determinístico.
C) Autômato com Pilha Não Determinístico.
D) Máquina de Turing Decididora.
E) Máquina de Turing Reconhecedora.
--------------------------------------------------

QUESTÃO 37:
Qual é a Expressão Regular (ER) que denota a linguagem a seguir?

𝐿= {𝑤∈{𝑎, 𝑏}∗ | 𝑤 𝑛ã𝑜 𝑝𝑜𝑑𝑒 𝑡𝑒𝑟𝑚𝑖𝑛𝑎𝑟 𝑐𝑜𝑚 𝑏𝑎}

OPÇÕES:
A) ¬( (𝑎∪𝑏)∗𝑏𝑎 )
B) (𝑎∪𝑏)∗𝑏𝑎
C) (𝑎∪𝑏)∗−( (𝑎∪𝑏)∗𝑏𝑎 )
D) ( (𝑎∪𝑏)∗(𝑏∪𝑎𝑎) ) ∪𝑎∪𝜆
E) A linguagem L não é regular e, portanto, não pode ser denotada por uma ER.
--------------------------------------------------

QUESTÃO 38:
Dada a linguagem 𝐿= {𝑤∈{𝑎, 𝑏}∗ | 𝑜 𝑡𝑒𝑟𝑐𝑒𝑖𝑟𝑜 ú𝑙𝑡𝑖𝑚𝑜 𝑠í𝑚𝑏𝑜𝑙𝑜 𝑑𝑒 𝑤 é 𝑎}, analise as
assertivas abaixo, assinalando V, se verdadeiras, ou F, se falsas.

(  ) O menor Autômato Finito Não Determinístico (AFND) que reconhece L tem 4 (quatro) estados.
(  ) O Autômato Finito Determinístico (AFD) que reconhece L tem, no mínimo, 8 (oito) estados.
(  ) A menor Gramática Regular (GR) que gera L tem 3 (três) não terminais.
(  ) O conjunto regular {𝑎, 𝑏}∗{𝑎}{𝑎, 𝑏}{𝑎, 𝑏} denota L.

A ordem correta de preenchimento dos parênteses, de cima para baixo, é:

OPÇÕES:
D) que reconhece L tem 4 (quatro) estados. ( ) O Autômato Finito Determinístico (AFD) que reconhece L tem, no mínimo, 8 (oito) estados. ( ) A menor Gramática Regular (GR) que gera L tem 3 (três) não terminais. ( ) O conjunto regular {𝑎, 𝑏}∗{𝑎}{𝑎, 𝑏}{𝑎, 𝑏} denota L. A ordem correta de preenchimento dos parênteses, de cima para baixo, é:
A) F – F – V – V.
B) V – V – V – V.
C) F – V – F – V.
D) V – V – F – F.
E) V – F – V – F.
--------------------------------------------------

QUESTÃO 39:
Nos arquivos ordenados, os registros são dispostos fisicamente no disco de acordo
com os valores de um de seus campos: o campo de ordenação (chave). Analise as seguintes
assertivas sobre arquivos ordenados:

I. A leitura dos registros na ordem dos valores da chave de ordenação é mais eficiente se
comparada à leitura desses registros em arquivos heap.
II. Permite atender de forma eficiente condições de pesquisa sobre o campo de ordenação no
formato <chave = valor> ou condição de intervalo (isto é, a chave estar no intervalo entre o
valor1 e valor2).
III. Para acelerar o acesso a um registro baseado no valor de uma chave em arquivos ordenados, a
melhor técnica de pesquisa é a técnica de hash.

Quais estão corretas?

OPÇÕES:
A) Apenas I.
B) Apenas II.
C) Apenas III.
D) Apenas I e II.
E) I, II e III.
--------------------------------------------------

QUESTÃO 40:
Os sistemas operacionais mantêm várias informações sobre cada arquivo, chamadas
de metadados. Assinale o atributo que NÃO é um metadado de arquivo gerenciado pelo sistema
operacional.

OPÇÕES:
A) Data da criação do arquivo.
B) Tamanho do registro (ex.: número em bytes do registro).
C) Tamanho atual do arquivo (ex.: número máximo em bytes do arquivo).
D) Flag (indicador) de tipo de arquivo (ex.: sistema/normal).
E) Nome dos diferentes campos lógicos representados nos registros dos arquivos (ex.: id, nome, data de nascimento, nome da mãe, RG, etc.).
--------------------------------------------------

QUESTÃO 41:
Um desenvolvedor de software armazenou registros representando tweets em um
arquivo. Ele optou por utilizar uma árvore trie como índice desse arquivo para tornar eficientes
alguns tipos de busca de tweets contendo palavras de determinada natureza. Sobre o uso de árvores
trie, analise as assertivas abaixo e assinale V, se verdadeiras, ou F, se falsas.


In [18]:
import pandas as pd
import numpy as np
import csv

In [19]:
df = pd.DataFrame(questoes)
df

,numero,pergunta,opcoes
0,01,Utilize o método de Eliminação de Gauss para r...,"[A) (0, -1, 2), B) (0, 1, 0), C) (2, 0, 2), D)..."
1,02,"Determine o valor de x para que o vetor (1, x,...","[A) x = 0, B) x = -1, C) x = 1, D) x = 3, E) x..."
2,03,Determine o polinômio característico de J: \n ...,"[A) 0, B) x, C) (1 − x), D) (1 − x)², E) (1 − ..."
3,04,"Nos jogos da Mega-Sena, são sorteados a cada c...","[A) 56, B) 8!, C) 6!, D) 28, E) 72]"
4,05,"Recentemente, com a pandemia de Covid-19, houv...","[A) 1024, B) 10, C) 100, D) 512, E) 20]"
...,...,...,...
65,66,Qual dispositivo atua somente nas camadas físi...,"[A) Hub., B) Roteador., C) Repetidor., D) Gate..."
66,67,"Considere um pacote de p bytes, enviados por u...","[A) c/b, B) b/c, C) 8p/b, D) d/c, E) d/c + b/c]"
67,68,Uma transação cliente se torna distribuída se ...,"[A) plana, B) aninhada, C) coordenadora, D) em..."
68,69,"Em sistemas operacionais distribuídos, é corre...","[A) No escalonamento não preemptivo, uma threa..."
69,70,Sobre comunicação indireta em sistemas distrib...,[A) A comunicação direta é definida como a com...

In [105]:
df.loc[19, 'pergunta'] = 'Para responder à questao, utilize a seguinte lista de dados, correspondente ao número de segundos que um software precisa para resolver um cálculo matemático: 60; 66; 77; 70; 66; 68; 57; 70; 66; 52; 75; 65; 69; 71; 58; 66; 67; 74; 61; 63; 69; 80; 59; 66; 70; 67; 78; 75; 64; 71; 81; 62; 64; 69; 68; 72; 83; 56; 65; 74; 67; 54; 65; 65; 69; 61; 67; 73; 57; 62; 67; 68; 63; 67; 71; 68; 76; 61; 62; 63; 76; 61; 67; 67; 64; 72; 64; 73; 79; 58; 67; 71; 68; 59; 69; 70; 66; 62; 63; 66; O tempo médio aproximado, que o software leva para realizar os cálculos é:'

In [117]:
df.loc[53].pergunta

'Analise as matrizes de transformações geométricas A e B. \n \n𝑨:     [\n𝑥′\n𝑦′\n1\n] = [\ncos (𝜃)\n−𝑠𝑒𝑛(𝜃)\n0\n𝑠𝑒𝑛(𝜃)\ncos (𝜃)\n0\n0\n0\n1\n] ∙[\n𝑥\n𝑦\n1\n] \n \n𝑩:     [\n𝑥′\n𝑦′\n1\n] = [\n𝐸𝑥\n0\n𝑇𝑥\n0\n𝐸𝑦\n𝑇𝑦\n0\n0\n1\n] ∙[\n𝑥\n𝑦\n1\n] \n \nConsiderando que 𝐸𝑥 e 𝐸𝑦 são fatores de escala, 𝑇𝑥 e 𝑇𝑦 são fatores de translação e que 𝜃 representa \num ângulo de rotação, analise as assertivas a seguir: \n \nI. A transformação 𝑨 rotaciona o objeto com pivô no centro de massa do próprio objeto. \nII. A transformação 𝑩 primeiro escala e depois translada o objeto. \n \nQuais estão corretas?'

In [136]:
# Nova linha como DataFrame
nova_linha = pd.DataFrame({'numero': [46], 'pergunta': ['''Analise as assertivas abaixo sobre estruturas em linguagens de programação: I. Uma estrutura é um conjunto de uma ou mais variáveis agrupadas sob um único nome, de forma a facilitar a sua referência.
II. A declaração de uma estrutura corresponde unicamente à definição de um novo tipo (isto é, da sua estrutura), e não à declaração de variáveis do tipo da estrutura.
III. Uma estrutura pode conter, na sua definição, variáveis simples, vetores, ponteiros ou mesmo outras estruturas.
IV. As estruturas permitem agrupar diversos componentes em uma única variável, que podem ser definidos com tipos distintos.
Quais estão corretas?'''], 'opcoes': [["A) (W+X)*( W̅ + X̅ + Y + Z)*( Y̅ + Z̅)",
"B) (W+ X̅+ Z̅)*(W+X+ Z̅ )*(W̅ + X̅ )*(Y̅ + Z)",
"C) (W̅ + X)*(W+Y+ Z̅)*(W+Y̅ +Z)* *(W+X̅ + Y̅ )",
"D) (W+X)*(W̅ + Y̅ + Z̅)",
"E) (W+X)*(W̅ + Y̅ + Z̅)*(W̅ + X̅ + Y + Z)"]]})

# Dividir e concatenar
df_final = pd.concat([
    df.iloc[:45], 
    nova_linha, 
    df.iloc[45:]
], ignore_index=True)

In [138]:
df_final.tail(40)
df = df_final

In [141]:
df.tail(40)
df = df[['numero','pergunta','opcoes']]

In [20]:
df.to_csv(
    'poscomp-23.csv',
    index=False,          # Não incluir índice
    sep=',',              # Delimitador padrão (vírgula)
    quoting=csv.QUOTE_ALL, # Forçar aspas em todos os campos
    quotechar='"',        # Usar aspas duplas para encapsular
    escapechar='\\',      # Escapar caracteres especiais se necessário
    encoding='utf-8'      # Codificação para preservar caracteres especiais
)
df

,numero,pergunta,opcoes
0,01,Utilize o método de Eliminação de Gauss para r...,"[A) (0, -1, 2), B) (0, 1, 0), C) (2, 0, 2), D)..."
1,02,"Determine o valor de x para que o vetor (1, x,...","[A) x = 0, B) x = -1, C) x = 1, D) x = 3, E) x..."
2,03,Determine o polinômio característico de J: \n ...,"[A) 0, B) x, C) (1 − x), D) (1 − x)², E) (1 − ..."
3,04,"Nos jogos da Mega-Sena, são sorteados a cada c...","[A) 56, B) 8!, C) 6!, D) 28, E) 72]"
4,05,"Recentemente, com a pandemia de Covid-19, houv...","[A) 1024, B) 10, C) 100, D) 512, E) 20]"
...,...,...,...
65,66,Qual dispositivo atua somente nas camadas físi...,"[A) Hub., B) Roteador., C) Repetidor., D) Gate..."
66,67,"Considere um pacote de p bytes, enviados por u...","[A) c/b, B) b/c, C) 8p/b, D) d/c, E) d/c + b/c]"
67,68,Uma transação cliente se torna distribuída se ...,"[A) plana, B) aninhada, C) coordenadora, D) em..."
68,69,"Em sistemas operacionais distribuídos, é corre...","[A) No escalonamento não preemptivo, uma threa..."
69,70,Sobre comunicação indireta em sistemas distrib...,[A) A comunicação direta é definida como a com...