In [6]:
import pandas as pd
import numpy as np
import csv
from pandas import json_normalize

In [11]:
rc1 = [
	{"numero": 1, "resposta": "D) (-7/5, -2, -21/5)"},
	{"numero": 2, "resposta": "B) α = 2"},
	{"numero": 3, "resposta": "E) – (λ – 2)³"},
	{"numero": 4, "resposta": "B) 8."},
	{"numero": 5, "resposta": "A) 6."},
	{"numero": 6, "resposta": "D) 285."},
	{"numero": 7, "resposta": "C) 0"},
	{"numero": 8, "resposta": "C) [-2, 1/3) U (1/3, 2]"},
	{"numero": 9, "resposta": "D) 1/2"},
	{"numero": 10, "resposta": "B) (9/2, -3/2)"},
	{"numero": 11, "resposta": "A) k = 3 e k = 7"},
	{"numero": 12, "resposta": "E) As retas são paralelas e não possuem ponto de intersecção."},
	{"numero": 13, "resposta": "D) q→p"},
	{"numero": 14, "resposta": "A) p e q"},
	{"numero": 15, "resposta": "B) Hoje não é sábado e Joaquim não jogou videogame."},
	{"numero": 16, "resposta": "D) 𝐴𝐶̅ + 𝐵̅𝐷"},
	{"numero": 17, "resposta": "C) 𝑓= 𝑎′𝑏+ 𝑐"},
	{"numero": 18, "resposta": "B) (𝐴𝐵+ 𝐵) ̅̅̅̅̅̅̅̅̅̅̅̅"},
	{"numero": 19, "resposta": "D) 36.3%"},
	{"numero": 20, "resposta": "C) 67."}
]


df1 = pd.DataFrame(rc1)
df1

    numero                                           resposta
0        1                               D) (-7/5, -2, -21/5)
1        2                                           B) α = 2
2        3                                      E) – (λ – 2)³
3        4                                              B) 8.
4        5                                              A) 6.
5        6                                            D) 285.
6        7                                               C) 0
7        8                            C) [-2, 1/3) U (1/3, 2]
8        9                                             D) 1/2
9       10                                     B) (9/2, -3/2)
10      11                                   A) k = 3 e k = 7
11      12  E) As retas são paralelas e não possuem ponto ...
12      13                                             D) q→p
13      14                                           A) p e q
14      15  B) Hoje não é sábado e Joaquim não jogou video...
15      16                                       D) 𝐴𝐶̅ + 𝐵̅𝐷
16      17                                       C) 𝑓= 𝑎′𝑏+ 𝑐
17      18                            B) (𝐴𝐵+ 𝐵) ̅̅̅̅̅̅̅̅̅̅̅̅
18      19                                           D) 36.3%
19      20                                             C) 67.

In [12]:
rc2 = [
	{"numero": 21, "resposta": "A) O caso médio é f(n) = (n + 1)/2"},
	{"numero": 22, "resposta": "E) Analisar o comportamento do algoritmo à medida que o tamanho da entrada aumenta indefinidamente."},
	{"numero": 23, "resposta": "B) O(1) e O(n)."},
	{"numero": 24, "resposta": "E) simplesmente encadeada ordenada"},
	{"numero": 25, "resposta": "B) O corpo do laço do...while é executado pelo menos uma vez, enquanto nos laços while e for o corpo do laço pode nunca ser executado (caso a condição seja falsa a priori)."},
	{"numero": 26, "resposta": "D) pré-fixado"},
	{"numero": 27, "resposta": "A) Endereço total de 19 bits, com tag = 8 bits, s = 12 bits, d = 4 bits e w = 7 bits."},
	{"numero": 28, "resposta": "C) Apenas III."},
	{"numero": 29, "resposta": "D) Direct Memory Access (DMA)."},
	{"numero": 30, "resposta": "C) ∑m(4, 5, 6, 7)"},
	{"numero": 31, "resposta": "E) (W+X)*(W̅ + Y̅ + Z̅)*(W̅ + X̅ + Y + Z)"},
	{"numero": 32, "resposta": "E) Máquina de Moore que detecta dois 1’s seguidos."},
	{"numero": 33, "resposta": "C) 4."},
	{"numero": 34, "resposta": "A) A saída é o número de caracteres de “str” dividido por 2, mostrado como um número de ponto flutuante."},
	{"numero": 35, "resposta": "D) Os métodos +print() das classes Ponto e Círculo."},
	{"numero": 36, "resposta": "C) {w ∈ {a, b}* | o número de a’s em w é divisível por 3 e o número de b’s é ímpar}."},
	{"numero": 37, "resposta": "B) Apenas IV."},
	{"numero": 38, "resposta": "B) Teorema da Incompletude – Kurt Gödel – Problema da Parada – Alan Turing"},
	{"numero": 39, "resposta": "C) Na memória secundária, o sistema operacional armazena informações em grupos, chamados blocos, para aumentar a eficiência na transferência de dados entre a memória secundária e a memória principal."},
	{"numero": 40, "resposta": "A) A compressão de dados pode ser alcançada atribuindo descrições curtas aos resultados mais frequentes da fonte de dados e necessariamente descrições mais longas aos resultados menos frequentes."}
]

df2 = pd.DataFrame(rc2)
df2

    numero                                           resposta
0       21                 A) O caso médio é f(n) = (n + 1)/2
1       22  E) Analisar o comportamento do algoritmo à med...
2       23                                    B) O(1) e O(n).
3       24                 E) simplesmente encadeada ordenada
4       25  B) O corpo do laço do...while é executado pelo...
5       26                                      D) pré-fixado
6       27  A) Endereço total de 19 bits, com tag = 8 bits...
7       28                                     C) Apenas III.
8       29                     D) Direct Memory Access (DMA).
9       30                                  C) ∑m(4, 5, 6, 7)
10      31          E) (W+X)*(W̅ + Y̅ + Z̅)*(W̅ + X̅ + Y + Z)
11      32  E) Máquina de Moore que detecta dois 1’s segui...
12      33                                              C) 4.
13      34  A) A saída é o número de caracteres de “str” d...
14      35  D) Os métodos +print() das classes Ponto e Cír...
15      36  C) {w ∈ {a, b}* | o número de a’s em w é divis...
16      37                                      B) Apenas IV.
17      38  B) Teorema da Incompletude – Kurt Gödel – Prob...
18      39  C) Na memória secundária, o sistema operaciona...
19      40  A) A compressão de dados pode ser alcançada at...

In [13]:
rc3 = [
	{"numero": 41, "resposta": "C) Apenas a assertiva III está correta."},
	{"numero": 42, "resposta": "E) tratadores de interrupção – controladores de dispositivo – controladores de dispositivo"},
	{"numero": 43, "resposta": "C) lbm ≤ 10"},
	{"numero": 44, "resposta": "C) Tamanho de bloco = 1.024 bytes e sistema de arquivos baseado em alocação indexada."},
	{"numero": 45, "resposta": "A) As variáveis do tipo inteiro são utilizadas para armazenar valores que pertencem ao conjunto de números naturais (sem parte fracionária) positivos e negativos."},
	{"numero": 46, "resposta": "D) (W+X)*(W̅ + Y̅ + Z̅)"},
	{"numero": 47, "resposta": "D) Condicional encadeada."},
	{"numero": 48, "resposta": "C) Grafo misto."},
	{"numero": 49, "resposta": "A) Paralelas."},
	{"numero": 50, "resposta": "B) ciclo"},
	{"numero": 51, "resposta": "C) 4 tuplas."},
	{"numero": 52, "resposta": "B) Grafo de espera."},
	{"numero": 53, "resposta": "D) Apenas II, III e IV."},
	{"numero": 54, "resposta": "E) Gramática livre de contexto na qual fragmentos de programas (ações) são inseridos nos lados direitos das regras de produção."},
	{"numero": 55, "resposta": "D) Apenas I, II e III."},
	{"numero": 56, "resposta": "B) Apenas II."},
	{"numero": 57, "resposta": "B) Todas as assertivas estão incorretas."},
	{"numero": 58, "resposta": "A) Aumentar a complexidade dos processos de negócios."},
	{"numero": 59, "resposta": "D) Especificação de software."},
	{"numero": 60, "resposta": "A) Todas as assertivas estão corretas."}
]

df3 = pd.DataFrame(rc3)
df3

    numero                                           resposta
0       41            C) Apenas a assertiva III está correta.
1       42  E) tratadores de interrupção – controladores d...
2       43                                        C) lbm ≤ 10
3       44  C) Tamanho de bloco = 1.024 bytes e sistema de...
4       45  A) As variáveis do tipo inteiro são utilizadas...
5       46                            D) (W+X)*(W̅ + Y̅ + Z̅)
6       47                          D) Condicional encadeada.
7       48                                    C) Grafo misto.
8       49                                      A) Paralelas.
9       50                                           B) ciclo
10      51                                       C) 4 tuplas.
11      52                                B) Grafo de espera.
12      53                            D) Apenas II, III e IV.
13      54  E) Gramática livre de contexto na qual fragmen...
14      55                             D) Apenas I, II e III.
15      56                                      B) Apenas II.
16      57           B) Todas as assertivas estão incorretas.
17      58  A) Aumentar a complexidade dos processos de ne...
18      59                      D) Especificação de software.
19      60             A) Todas as assertivas estão corretas.

In [14]:
rc4 = [
	{"numero": 61, "resposta": "E) Combinar partes dos cromossomos de dois pais para criar descendentes."},
	{"numero": 62, "resposta": "C) O motor de inferência utiliza as regras definidas na base de conhecimento para derivar conclusões a partir de fatos específicos, simulando o raciocínio humano especializado."},
	{"numero": 63, "resposta": "D) amostragem – quantização"},
	{"numero": 64, "resposta": "B) Apenas I e III."},
	{"numero": 65, "resposta": "E) 11.1.2.0/24"},
	{"numero": 66, "resposta": "D) Várias cópias de um pacote IP podem ser entregues."},
	{"numero": 67, "resposta": "E) UDP"},
	{"numero": 68, "resposta": "B) Acesso."},
	{"numero": 69, "resposta": "E) por queda"},
	{"numero": 70, "resposta": "A) centralizado"}
]

df4 = pd.DataFrame(rc4)
df4

   numero                                           resposta
0      61  E) Combinar partes dos cromossomos de dois pai...
1      62  C) O motor de inferência utiliza as regras def...
2      63                        D) amostragem – quantização
3      64                                 B) Apenas I e III.
4      65                                     E) 11.1.2.0/24
5      66  D) Várias cópias de um pacote IP podem ser ent...
6      67                                             E) UDP
7      68                                         B) Acesso.
8      69                                       E) por queda
9      70                                    A) centralizado

In [15]:
df = pd.concat([df1,df2,df3,df4], ignore_index=True)
df

    numero                                           resposta
0        1                               D) (-7/5, -2, -21/5)
1        2                                           B) α = 2
2        3                                      E) – (λ – 2)³
3        4                                              B) 8.
4        5                                              A) 6.
..     ...                                                ...
65      66  D) Várias cópias de um pacote IP podem ser ent...
66      67                                             E) UDP
67      68                                         B) Acesso.
68      69                                       E) por queda
69      70                                    A) centralizado

[70 rows x 2 columns]

In [16]:
df.to_csv(
    'ds_resp_pc.csv',
    index=False,          # Não incluir índice
    sep=',',              # Delimitador padrão (vírgula)
    quoting=csv.QUOTE_ALL, # Forçar aspas em todos os campos
    quotechar='"',        # Usar aspas duplas para encapsular
    escapechar='\\',      # Escapar caracteres especiais se necessário
    encoding='utf-8'      # Codificação para preservar caracteres especiais
)