In [1]:
import pandas as pd
import csv
import numpy as np

In [2]:
df = pd.DataFrame()
df_respostas3 = df.copy()
df_respostas3["resposta"] = [
    "A) Todas as assertivas estão corretas.",
    "B) O escalonador de E/S gerencia a ordem de execução das solicitações.",
    "C) lbm ≤ 10",
    "D) Tamanho de bloco = 4.096 bytes e sistema de arquivos compatível.",
    "C) Tipos primitivos dependem da linguagem e arquitetura.",
    "B) Expressão minimizada correta.",
    "D) Estrutura de repetição encadeada.",
    "C) Grafo ponderado.",
    "B) Laços.",
    "B) Ciclo.",
    "D) 5 tuplas.",
    "C) Algoritmo do grafo de espera.",
    "A) Apenas I, II e III.",
    "D) Autômato e gramática associada.",
    "C) Apenas I e III.",
    "D) Apenas I e II.",
    "A) Todas as assertivas estão corretas.",
    "D) Reduzir riscos e melhorar previsibilidade.",
    "B) Validação e verificação.",
    "A) Todas as assertivas estão corretas.",
]

In [3]:
df_respostas3

                                             resposta
0              A) Todas as assertivas estão corretas.
1   B) O escalonador de E/S gerencia a ordem de ex...
2                                         C) lbm ≤ 10
3   D) Tamanho de bloco = 4.096 bytes e sistema de...
4   C) Tipos primitivos dependem da linguagem e ar...
5                    B) Expressão minimizada correta.
6                D) Estrutura de repetição encadeada.
7                                 C) Grafo ponderado.
8                                           B) Laços.
9                                           B) Ciclo.
10                                       D) 5 tuplas.
11                   C) Algoritmo do grafo de espera.
12                             A) Apenas I, II e III.
13                 D) Autômato e gramática associada.
14                                 C) Apenas I e III.
15                                  D) Apenas I e II.
16             A) Todas as assertivas estão corretas.
17      D) Reduzir riscos e melhorar previsibilidade.
18                        B) Validação e verificação.
19             A) Todas as assertivas estão corretas.

In [7]:
df = pd.DataFrame()
df_respostas2 = df.copy()
df_respostas2["resposta"] = [
    "A) O caso médio é f(n) = (n + 1)/2",  # Questão 21
    "B) Analisar o crescimento assintótico do tempo de execução",  # Questão 22
    "B) O(1) para inserção e O(n) para busca",  # Questão 23
    "A) Lista duplamente encadeada",  # Questão 24
    "C) Descrição correta do funcionamento do while e for",  # Questão 25
    "A) Caminhamento pré-ordem",  # Questão 26
    "B) Tag, índice e deslocamento corretamente definidos",  # Questão 27
    "C) Explicação correta das funções dos chipsets",  # Questão 28
    "B) DMA (Acesso Direto à Memória)",  # Questão 29
    "C) Expressão simplificada correta da função booleana",  # Questão 30
    "A) Forma fatorada correta da função booleana",  # Questão 31
    "B) Máquina de Mealy que computa um somador simples",  # Questão 32
    "C) Saída correta do código em C",  # Questão 33
    "C) Saída correta do código em C",  # Questão 34
    "A) Relacionamento correto entre classes UML",  # Questão 35
    "B) Linguagens regulares geradas por autômatos finitos",  # Questão 36
    "C) Hierarquia de Chomsky aplicada corretamente",  # Questão 37
    "A) Teorema da Incompletude – Kurt Gödel",  # Questão 38
    "B) Diferença entre arquivos estruturados e não estruturados",  # Questão 39
    "A) Compressão com perdas e sem perdas",  # Questão 40
]

In [8]:
df_respostas2

                                             resposta
0                  A) O caso médio é f(n) = (n + 1)/2
1   B) Analisar o crescimento assintótico do tempo...
2             B) O(1) para inserção e O(n) para busca
3                       A) Lista duplamente encadeada
4   C) Descrição correta do funcionamento do while...
5                           A) Caminhamento pré-ordem
6   B) Tag, índice e deslocamento corretamente def...
7      C) Explicação correta das funções dos chipsets
8                    B) DMA (Acesso Direto à Memória)
9   C) Expressão simplificada correta da função bo...
10       A) Forma fatorada correta da função booleana
11  B) Máquina de Mealy que computa um somador sim...
12                    C) Saída correta do código em C
13                    C) Saída correta do código em C
14        A) Relacionamento correto entre classes UML
15  B) Linguagens regulares geradas por autômatos ...
16     C) Hierarquia de Chomsky aplicada corretamente
17            A) Teorema da Incompletude – Kurt Gödel
18  B) Diferença entre arquivos estruturados e não...
19              A) Compressão com perdas e sem perdas

In [9]:
df_respostas1 = pd.read_csv('/kaggle/input/resps-gpt-1-4/respostas_poscomp_24_b1.csv')

In [10]:
df_respostas1['resposta'] = df_respostas1['Resposta']
df_respostas1 = df_respostas1.drop(['Resposta'], axis=1)

In [11]:
df_respostas1

                                     resposta
0                           A) (1/5, -1, 2/5)
1                                    A) α = 1
2                                  A) (λ – 2)
3                                       A) 6.
4                                       A) 6.
5                                      A) 70.
6                                       A) -∞
7                         A) [-4, 1) U (1, 4]
8                                        A) e
9                               A) (1/2, 1/2)
10                           A) k = 3 e k = 7
11                                 A) (-3, 1)
12                                   A) ~q∧~p
13                                   A) p e q
14  A) Hoje é sábado e Ana Paula jogou vôlei.
15                                 A) 𝐴𝐶̅ + 𝐵
16                              A) 𝑓= 𝑎′𝑏+ 𝑎𝑏
17                A) (𝐴𝐵+ 𝐵)𝐵̅ ̅̅̅̅̅̅̅̅̅̅̅̅̅̅
18                                   A) 28,8%
19                                     A) 65.

In [12]:
df_respostas4 = pd.read_csv('/kaggle/input/resps-gpt-1-4/respostas_poscomp_24_b4.csv')

In [13]:
df_respostas4 = df_respostas4.drop(['pergunta', 'opcoes', 'numero'], axis=1)

In [14]:
df_respostas4

                                            resposta
0  A) Avaliar a aptidão de cada indivíduo na popu...
1  A) O motor de inferência atua principalmente s...
2                       A) interpolação – ampliação.
3                                C) Apenas II e III.
4                                      A) 13.0.0.0/8
5  A) O protocolo IP é baseado em datagramas e nã...
6                                       A) TCP e UDP
7                                    A) Localização.
8                                B) de temporização.
9                                   A) centralizado.

In [15]:
df_resps = pd.concat([df_respostas1,df_respostas2,df_respostas3,df_respostas4], ignore_index=True)

In [16]:
df_resps

                                             resposta
0                                   A) (1/5, -1, 2/5)
1                                            A) α = 1
2                                          A) (λ – 2)
3                                               A) 6.
4                                               A) 6.
..                                                ...
65  A) O protocolo IP é baseado em datagramas e nã...
66                                       A) TCP e UDP
67                                    A) Localização.
68                                B) de temporização.
69                                   A) centralizado.

[70 rows x 1 columns]

In [17]:
df_resps.to_csv(
    'gpt_resp_pc.csv',
    index=False,          # Não incluir índice
    sep=',',              # Delimitador padrão (vírgula)
    quoting=csv.QUOTE_ALL, # Forçar aspas em todos os campos
    quotechar='"',        # Usar aspas duplas para encapsular
    escapechar='\\',      # Escapar caracteres especiais se necessário
    encoding='utf-8'      # Codificação para preservar caracteres especiais
)